### ISSUE TITLE
How to deploy freqtrade UI on a server (and authentication) to use UI everywhere?

### ISSUE THREAD

**Issue by gaugau3000** [freqtrade/frequi#10]
Hi,

I have take a look at current development your local dev server proxy http requests and get access to back end witch his on the same localhost and not need authentification.

If i want to deploy freqtrade UI on a server I need a screen where i can logging API info ?

How to you see that ?

**Comment by xmatthias** [comment]
deployment is not yet done - keep in mind that this project is in early alpha phase, and only people comfortable running it via `npm run serve` should use it (until it reaches a certain maturity).


As mentioned elsewhere - the plan for deployment is as part of freqtrade - so you run `freqtrade trade ..` - with apiserver=true - and the UI will then be available as `http://localhost:8080/ui`.

A standalone approach (deployment in a separate docker container) might also be possible.

For now, i can only recommend to NOT deploy this to a internet-facing port.

>  I need a screen where i can logging API info ?

FreqUI has a login page already (to login via api-url, username and password) - so i'm not sure what exactly you're asking for ... ?
