### ISSUE TITLE
Add candle percent change to info panel in graphs

### ISSUE THREAD

**Issue by HekutoruMAC** [freqtrade/frequi#1024]
Add candle percent change to info panel in graphs, alongside volume and ohlc data.

**Comment by xmatthias** [comment]
it's not clear what exactly you're looking for.

Please provide some more detail (or screenshots from alternative solutions that provide this) to clarify your request
thanks.

**Comment by xmatthias** [comment]
I'd not know what this represents - is it the candle range (low - high) - or open-close, ... it's therefore not really useful information.


You can however easily do this for your bot by creating a column in your strategy based on your liking (name and calculate as you'd like) - and then configuring freqUI to display that column (most likely in a separate plot at the bottom).
