### ISSUE TITLE
Auto add running strategies to the UI

### ISSUE THREAD

**Issue by karimelgazar** [freqtrade/frequi#1031]
Hi there, 
I have multiple strategies that run together at the same time but when I launch the UI app I need to manually add the running strategies so I can visualize their trades 

So my question here is there any API or endpoint that I can call to post the strategy data and automatically add it to the UI app before I open it on the browsers 

Thanks

**Comment by xmatthias** [comment]
Each strategy will run in it's own bot instance.
Each bot can (and should) have different credentials / a different port.

Credentials are stored in your browser. You can in theory mess with the application store - but that's highly discouraged / not supported.

This is therefore not possible. 
The UI also can't get this info from the bot (then everyone else able to connect to your bot could, too) for security reasons.
