### ISSUE TITLE
Support area graphs (like Bollinger Bands)

### ISSUE THREAD

**Issue by xmatthias** [freqtrade/frequi#107]
**Is your feature request related to a problem? Please describe.**
Current graphs don't support Area charts.

These would be useful for things like Bollinger Bands (or 70/30 lines in RSI subplots).

**Details**

It's currently unclear how eCharts can support this - as current solutions / [samples](https://echarts.apache.org/examples/en/editor.html?c=confidence-band)  shift the base for the lower chart.

Research indicates that it might be possible by using a [custom series](https://stackoverflow.com/questions/61724715/echarts-plot-the-variance-of-signals) for this - however further research is absolutely necessary.

There are also [open issues](https://github.com/apache/incubator-echarts/issues/9317) (and others) which discuss supporting area-charts natively - but i don't think implementation of this are very far yet.

**Comment by devsmitra** [comment]
@xmatthias 
Just a thought can we add a tradingview light chart. I have added a package link for reference. because most users are familiar with tradingview this could help. 

https://github.com/tradingview/lightweight-charts

**Comment by xmatthias** [comment]
from a license perspective - most likely no. (there's also very little information on the proprietary license that would apply to this).


We'd have to use the "lowest" version available [lightweight chart](https://www.tradingview.com/HTML5-stock-forex-bitcoin-charting-library/), as all others would not allow us to distribute it the way we are.
You'll therefore have very little benefit from it, but all the drawbacks (no synced / linked subcharts like RSI, ...).
That limitation applies to all Free libraries from tradingview.

It'd not look or feel like the tradingview library you're accustomed to.

**Comment by workingxx92** [comment]
@xmatthias .

How to config fill area bg color for senkou_a to senkou_b?
Thanks

**Comment by xmatthias** [comment]
FreqUI currently does not support band-like graphs.

**Comment by workingxx92** [comment]
Did you have plan for it?
