### ISSUE TITLE
freqtrade vue.js file and src folder not find

### ISSUE THREAD

**Issue by MalikAhmadA** [freqtrade/frequi#1071]
**Describe the bug**
i install the freqtrade ui using freqtrade install-ui command it chows that the freqtrade ui is already installed. when i go in to the folder i can't see any file name as app.vue the main file of ui in vuejs.
**Desktop (please complete the following information):**
 - OS: [e.g. linux (ubuntu)]
 - Browser [e.g. firefox]

**Comment by xmatthias** [comment]
i think you're missing how this is working.

by running `freqtrade install-ui` - you'll have the UI available on the defined port (if the [api is enabled](https://www.freqtrade.io/en/latest/rest-api/) - so you can (most likely) navigate to http://localhost:8080 (the default url) and have freqUI available there. That obviously assumes that freqtrade is running in either trade mode (`freqtrade trade <...>`) or in webserver mode (`freqtrade webserver <...>`).

`freqtrade install-ui` will install a built version of the UI - where only the html/js files necessary remain (in a compressed form). While it's still a vue application - there will be no vue files - everything is compressed to a few html/js files.
