### ISSUE TITLE
freqtrade ui setting with yarn

### ISSUE THREAD

**Issue by MalikAhmadA** [freqtrade/frequi#1072]
**Describe the bug**
i want to change the interface of freqtrade. i downloaded the freqtrade ui in my pc but in the assert folder there are many files except the vue file and other main files. this readme file of freqtrade ui is creating confusion how to set up the yarn and in which folder i setup the yarn and how.
**Desktop (please complete the following information):**
 - OS: [e.g. linux]
 - Browser [e.g. firefoxi]

**Comment by xmatthias** [comment]
You'll need to clone **this** repository (freqUI) - and then run the commands as specified in the readme within the project directory. (basically `git clone <repourl>` - followed by `cd <repo>` to get to the place to run all commands).

**Please note:**
The Readme of this project assumes some prior experience with using javascript tooling like Yarn (while we do have the basic commands in the readme - please research what they do to understand them properly).

Lacking this experience, please use your preferred learning method (videos, text, documentation, ...) to get a grasp about both yarn and Vue first.

While we are happy to help to some degree - we don't aim to replace self-education in this realm.
All tools used in freqUI are javascript standard toolings - so there's plenty of documentation and learning resources for that out there.

**Comment by MalikAhmadA** [comment]
and in which folder clone this git repo.freqtrade main or internal folder somewhere

**Comment by xmatthias** [comment]
Any directory on your pc will work.

Its not directly tied to freqtrade, and should be treated mostly separate.

**Comment by MalikAhmadA** [comment]
and how i attached this ui with my freqtrade strategies

**Comment by xmatthias** [comment]
you don't. 
as the readme states - the UI will run on port 3000 - and you'll need to configure CORS.

As you're trying to develop things (this is not a generic user task, but "i want to change core basics" - please **do your own research** into how the technologies you're trying to mess with works.
