### ISSUE TITLE
Add clear documentation how to configure FreqUI with freqtrade

### ISSUE THREAD

**Issue by xmatthias** [freqtrade/frequi#109]
**Is your feature request related to a problem? Please describe.**
Add clear documentation how to configure FreqUI with freqtrade (for standalone/development mode).

This will include (for example) links to the freqtrade CORS documentation..

**Describe alternatives you've considered**
Additionally, FreqUI should be built and deployed as part of freqtrade build steps (so it's builtin to freqtrade) - however this will require a few more things to happen, so is currently not yet an option.

**Comment by NilanjanaBala** [comment]
thanks for your all the effort for trying to build such a nice tool. I have configure it and i could see the frequi as http://localhost:8080/

I am in difficulties how to connect with my bot? I am not sure about what to put into the user name and password as we don't create any while configure our freqtrade bot. Could you please give some pointer?

**Comment by xmatthias** [comment]
well you MUST configure the bot to do it [as explained here](https://www.freqtrade.io/en/latest/rest-api/) - which also requires a username/password (the API is disabled by default).

to get the bot running, please also configure the [CORS Section](https://www.freqtrade.io/en/latest/rest-api/#cors) with `http://localhost:8080`.

**Comment by NilanjanaBala** [comment]
In bot config.json
    
"api_server": {
        "enabled": true,
        "listen_ip_address": "localhost",
        "listen_port": 8080,
        "verbosity": "info",
        "jwt_secret_key": "hello",
        "CORS_origins": [
            "http://localhost:8080"
        ],
        "username": "freq",
        "password": "freq"
    }

trying to log in : http://localhost:8080/

Getting the error as 
Login failed. Please verify that the bot is running, the Bot API is enabled and the URL is reachable. You can try this by going to http://http://localhost:8080/api/v1/ping

My bot is running and i could see it form telegram but not able to see it from frequi. Not sure what i am missing

thanks

**Comment by xmatthias** [comment]
are both bot and UI running on the same host?
If yes, then you must switch the port of one of the 2 from 8080 to something different...

**Comment by NilanjanaBala** [comment]
yes, its in same host. I tried the following again and getting same error

Put API url as : http://localhost:8081

frequi:
version: '3.8'
services:
  frequi:
    build:
      context: .
      dockerfile: "./Dockerfile"
    image: frequi
    # image: freqtradeorg/frequi:master
    restart: unless-stopped
    ports:
      - "8080:80"
Bot:
    "api_server": {
        "enabled": true,
        "listen_ip_address": "localhost",
        "listen_port": 8081,
        "verbosity": "info",
        "jwt_secret_key": "hello",
        "CORS_origins": [
            "http://localhost:8081"
        ],
        "username": "freq",
        "password": "freq"
    }

thanks

**Comment by xmatthias** [comment]
best open the browser's developer tools and check what call it's making / what error it's giving.

**Comment by NilanjanaBala** [comment]
Failed to load resource: net::ERR_CONNECTION_REFUSED
:8080/api/v1/token/login:1 Failed to load resource: the server responded with a status of 404 (Not Found)
Login.vue:145 Object
Login.vue:155 Login failed.
            Please verify that the bot is running, the Bot API is enabled and the URL is reachable.
            You can try this by going to http://http://localhost:8080/api/v1/ping
:8080/api/v1/token/login:1 Failed to load resource: the server responded with a status of 404 (Not Found)
Login.vue:145 Object
Login.vue:155 Login failed.
            Please verify that the bot is running, the Bot API is enabled and the URL is reachable.
            You can try this by going to http://http://localhost:8080/api/v1/ping
:8080/api/v1/token/login:1 Failed to load resource: the server responded with a status of 404 (Not Found)
Login.vue:145 Object
Login.vue:155 Login failed.
            Please verify that the bot is running, the Bot API is enabled and the URL is reachable.
            You can try this by going to http://http://localhost:8080/api/v1/ping
Login.vue:145 undefined
Login.vue:155 Login failed.
            Please verify that the bot is running, the Bot API is enabled and the URL is reachable.
            You can try this by going to http://http://localhost:8081/api/v1/ping
:8081/api/v1/token/login:1 Failed to lo

**Comment by xmatthias** [comment]
i think you've got the API url wrong - it shouldn't be `http://http://localhost:8080/` - but `http://localhost:8080/`.

**Comment by xmatthias** [comment]
Closed by 2c8bf13cf49433864b599e4bd408f3cc838ab4bf and 82cf57ad118c48608fbf5ae5994eb370113a379a  - which now link to the corresponding CORS documentation in freqtrade.
