### ISSUE TITLE
Trade-page => DailyStats-tab Profit% are 1/100th'st of what they should be

### ISSUE THREAD

**Issue by hippocritical** [freqtrade/frequi#1110]
**Describe the bug**
Current stable docker-container shows Profit% in the tradesWindow, DailyStats-Tab wrong by a factor of 100.

**Expected behavior**
both should state the same %age

**Screenshots**
frequi profit% from trade => daily stats tab:
![grafik](https://user-images.githubusercontent.com/41228167/215858121-4a5c78da-8508-41d7-beef-fd4dd5ffd6ae.png)
telegram /daily:
![grafik](https://user-images.githubusercontent.com/41228167/215858345-34b89a2f-1b8d-4ec6-9e02-1bad97b9b936.png)

**Desktop (please complete the following information):**
 - OS: linux mint
 - Browser firefox 109.0 + chromium 109.0.5414.119

**Comment by xmatthias** [comment]
interesting
seems aligned for me.
i'm on main - but nothing in the daily starts part changed in - like - months...

![image](https://user-images.githubusercontent.com/5024695/215867390-00b72ab4-663d-4351-a41d-e6474fdf5c3f.png)

![image](https://user-images.githubusercontent.com/5024695/215867432-0155d649-0088-453f-9f05-f85982526af1.png)

**Comment by xmatthias** [comment]
tested with freqtrade:stable - and still can't recreate this.

![image](https://user-images.githubusercontent.com/5024695/216424617-3787aa58-a067-4741-8951-b2c6852e50c8.png)


![image](https://user-images.githubusercontent.com/5024695/216424643-9e18c270-ab25-40b0-acc4-055c7bae9264.png)

can you try to FULLY reload the page (ctrl+F5)? to make sure there's nothing cached from an older version.

**Comment by xmatthias** [comment]
so it was a refresh problem? 
freqtrade:stable never included 0.6.3 ... ?

**Comment by hippocritical** [comment]
funny, definitely did a build --pull with the docker-container stable.
maybe just didn't do a ctrl+f5 and even after a boot this didnt fully refresh?
will check out the version and then report + close the issue if it is fixed.

**Comment by xmatthias** [comment]
hm - well if your bot is 2023.1 - the UI version will have to be 0.6.5, too.

browsers do cache files though - and if the tab wasn't reloaded (also a normal reload without ctrl should work) - then it's possible that the old state is still sticking around in your browser's cache.

**Comment by hippocritical** [comment]
mysterious... it was 2022.12, have to investivate why the command with docker-compose pull && docker-compose build && docker-compose build -pull didnt work ...

(doing both since then it wouldnt matter if it s just the image or if it s inside a dockerfile)... still, funny and weird ...
