### ISSUE TITLE
Show_config status change on stopentry

### ISSUE THREAD

**Issue by enshoe** [freqtrade/frequi#1130]
**Is your feature request related to a problem? Please describe.**
Currently I have set up a /reaload_config once my blacklist gets updated. This will override any /stopentry commands currently in force.

**Describe the solution you'd like**
If the /show_config "Current state" could reflect the /stopentry state. For instance "Current state: running (stopentry)"
This would make it possible to automate a check against it.

**Describe alternatives you've considered**
I have considered adding the changed pairs from my blacklist using the REST API. But that does not solve the issue with pairs that have been removed from the blacklist.

**Comment by xmatthias** [comment]
stopentry is not a bot state.

it's setting `max_open_trades` to 0 (preventing future entries) - which you can check for through the `/show_config` endpoint.

---

I don't really see your alternatives point though - `/blacklist` supports 3 verbs - "GET" to fetch current state - "POST" to put new pairs to the pairlist - and "DELETE" to delete pairs from the pairlist.

**Comment by enshoe** [comment]
Thanks for the guidence, automating towards max_open_trades will work fine.
That would save me having to compare and parse my updated blacklist, before send it in as POST/DELETE.
