### ISSUE TITLE
Backtesting via UI doesn't show errors

### ISSUE THREAD

**Issue by barrelman70** [freqtrade/frequi#1138]
When doing backtesting via the UI (http://localhost:8083/backtest), and there is an error in my strategy, the UI doesn't show that the backtest failed.  I have to check the terminal every time the results don't seem right (they don't change from the last run but I don't always realize this)

**Describe the solution you'd like**
The UI should at the very least show that the backtest failed.  It would be best if it could show the actual error like 

ValueError: Tried to merge a faster timeframe to a slower timeframe.This would create new rows, and can throw off your regular indicators.

**Describe alternatives you've considered**
Only alternative is to check the terminal window to see if an error occured

**Additional context**
Using UI 0.6.3

**Comment by xmatthias** [comment]
You can switch to the "logs" tab to see the log in the UI.

As space in the backtest window is already pretty tight, i don't think adding a log section there will make sense.

**Comment by barrelman70** [comment]
If I go to the logs tab and then back to the backtest tab, I lose all my backtest params.  I don't think we need the full error logs on the backtest tab, just an indication that the backtest failed.  There is already a spot that gives the status when the backtest is running, like "Backtest running: analyze 24.23%" So maybe instead of that spot being blank when the backtest is finished it just says Success/Failure or something along those lines.

**Comment by xmatthias** [comment]
i guess we can do that. 
It's currently however not passed by freqtrade, so while it's in the UI, it'll take a bit to be actually available.

**Comment by barrelman70** [comment]
Sweet thanks!  BTW I love having the backtest function in the GUI, makes life so much easier.  Thanks for all your hard work!
