### ISSUE TITLE
Allow customize candle colors

### ISSUE THREAD

**Issue by qiweiii** [freqtrade/frequi#1158]
**Is your feature request related to a problem? Please describe.**
Many users would be more used to other colors instead of `green/red`, for example I would prefer `red/green`

**Describe the solution you'd like**
Just like binance, there are a few options
<img width="331" alt="image" src="https://user-images.githubusercontent.com/32790369/223895382-4c40e547-249c-4d3b-b26a-1a41ed0fe7c7.png">

**Comment by xmatthias** [comment]
Defining matching colors that work for all the different scenarios is quite challenging (at least for me, as a non designer) - and quite honestly - not something i will be spending my time on.

Please note that for each "style" profile, we'll not just need 2 colors - but matching colors for
* entry/exit signals
* trades
* works on both light and dark theme


I'm more than happy to review a Pull request that will be adding this - but i don't intend to work on it myself.

**Comment by bukowa** [comment]
It would be interesting to assign colors to bars in a chart based on a category column in the dataframe. For example, you could define a set of colors in the user interface and then use the values in the "candle_color_category" column to map each bar to a corresponding color. Alternatively, you could directly use the values in the "candle_color" column to assign a color to each bar.
