### ISSUE TITLE
Bot managed balance showing wrong value

### ISSUE THREAD

**Issue by Mandark-droid** [freqtrade/frequi#1237]
**Describe the bug**
In FreqUI in the balance tab when looking at the bot managed balance its showing wrong value and due to that not allowing the bot to make any new entries. This issue is related to https://github.com/freqtrade/frequi/issues/1205

**To Reproduce**
1. Go to 'FreqUI trade > balance tab'
2. Click on 'Show bot balance'

Bot Balance
![image](https://user-images.githubusercontent.com/89932595/236734890-52d7347a-5376-4263-bd49-1ae500e62dd5.png)

Account balance:
![image](https://user-images.githubusercontent.com/89932595/236735599-6eeef65c-b231-4e01-ab10-cb7a882e25a0.png)

The actual USDT balance shown in the pie chart is correct but in the data table below is wrong and due to that on binance its not allowing the bot to enter a new trade since its assuming that the bot balance is less than 10$ where as in reality it has 17$ available. Also in the pie chart is showing 2 different tool tip balance for USDT which seems to be causing this issue. Kindly look into it. 

The freqtrade version used is latest develop.
![image](https://user-images.githubusercontent.com/89932595/236735157-0a896ce1-5102-4032-a408-30d1ee627af3.png)

Let me know if you need any further info.

**Comment by xmatthias** [comment]
Sounds like the pie-chart is showing the wrong value.

The table is almost certainly correct - the "bot balance" corresponds to what the bot can use - which is usually the account balance - 1% (can be configured via [`tradable_balance_ratio`](https://www.freqtrade.io/en/latest/configuration/#tradable-balance).

Will have a look at fixing the pie-chart display - but the functionality itself is correct :)

**Comment by Mandark-droid** [comment]
@xmatthias  If this is an issue that you are going to fix then why change the tag from bug to question.?

**Comment by Mandark-droid** [comment]
The [tradable_balance_ratio](https://www.freqtrade.io/en/latest/configuration/#tradable-balance) is set as 90% in my config. So 90% of 17.5 is 15.75 but its displaying 9.728 which is still wrong then how is it correct ?

**Comment by xmatthias** [comment]
it's a display glitch only - which is only affecting part of the tooltip (not the chart).

Keeping it as bug would be confusing to you (the issue author) - as you assume the bug is that it's not entering a trade because of this. 
The fix will however be to fix the tooltip display value - it'll not change how freqtrade works.

---

Your calculation basis is wrong. 90% will apply to the whole "usable" account (open bot trades + available USDT amount), not to 17$.

**Comment by Mandark-droid** [comment]
Its still a bug for me and not confusing since its assuming the available usdt amount is 9.7 and not entering a trade as its the same message I see in the freqtrade logs when I get an entry signal it says available balance is lower then 15$ however the mininum buy on binance is 10$. However its not the case there are funds available to enter a trade and its assuming that there aren't enough funds and not entering the trade.

**Comment by xmatthias** [comment]
The behavior of freqtrade is correct - it's the tooltip that's showing the wrong thing.
Relabing this as question here was 100% correct - as you're still confused as to what the actual wrong behavior here is (it's the tooltip showing a slightly wrong value - NOTHING ELSE).

It will not enter a trade for 10$ - as that would mean in case of a negative trade / stoploss - you'd be unable to exit the trade.
The **actual** limit is therefore closer to 15$ - assuming a pretty low default stake (which is clearly the case, on a 60$ account).
This is explained [in the documentation](https://www.freqtrade.io/en/stable/configuration/#minimum-trade-stake), which exactly explains your particular question.

**Comment by Mandark-droid** [comment]
For me the tooltip showing wrong value is still a bug and not a question if you ask me and relabeling it was not 100% correct as How can displaying wrong value be a question and not a bug?

**Comment by xmatthias** [comment]
As mentioned above  :) 

> Keeping it as bug would be confusing to you (the issue author) - as you assume the bug is that it's not entering a trade because of this.
> The fix will however be to fix the tooltip display value - it'll not change how freqtrade works.

your further comments fortified this statement / approach - as you clearly thought the bug was freqtrade's behavior (which is correct), and that the tooltip value was the only correct value

I don't see why the label is relevant, anyway. 
As mentioned before - if i wouldn't intend to fix it, i'd have closed the issue.

**Comment by Mandark-droid** [comment]
@xmatthias When will the docker image with the above commit be published as I checked on dockerhub the last image was published 5 hours before this commit.

**Comment by xmatthias** [comment]
It will be included in the develop docker images once we do a release of freqUI.

These happen at irregular intervals - but latest before the next stable release.
