### ISSUE TITLE
[FR] Show an indication of unrealized profit/loss in "Cumulative Profit" pane

### ISSUE THREAD

**Issue by VanessaE** [freqtrade/frequi#1251]
**Is your feature request related to a problem? Please describe.**

It is not related to a program problem, as such, but to a "social" problem. :stuck_out_tongue: 

**Describe the solution you'd like**

On the "Dashboard" page's "Cumulative Profit" pane, I think it would be useful to plot the unrealized profit/loss at the very end of the graph.

I suggest a simple dashed (or dotted) red or green line, drawn diagonally from the dot that marks the most recent closed trade, to another red/green dot positioned horizontally at today's date, i.e. "now".

The vertical position of the "now" dot/endpoint would be a relative USD/USDT/BTC/etc. amount above or below the last closed trade, according to the live unrealized profit/loss figure.  For example, if the last closed trade put the profit at +$200, and there's still an unrealized loss of -$50, then this dot/endpoint would be positioned vertically at $150.  Essentially, it would show where the graph will end up if all open trades were to immediately close.

By "unrealized", I mean of course the "Summary" figure in the "Bot Comparison" pane's "Open Profit" column.

Since the dates at the bottom of the graph are spaced-out a week apart, it would be a good idea to also ensure that today's date is always printed regardless of this spacing, provided there's room in the layout.

Obviously, the start of the line would have to update whenever another trade closes, and the "now" point would need to refresh periodically to keep its positioning up-to-date.

To avoid clutter, there should be only one item added to the legend at the top, which would just change color as the unrealized figure switches between profit and loss.  That or just draw the mark in both red and green, split half-and-half.

This idea was inspired by a discussion on the NFI Discord server, regarding how this graph can sometimes unintentionally mislead people about the profitability of the strategy (to say nothing of someone doing so deliberately).  I figured this idea would thoroughly shut down that complaint, since it would make the unrealized profit/loss obvious. 🙂

**Describe alternatives you've considered**

Since the idea is to make sure unrealized profit/loss is always disclosed when screenshots of this graph are shared (well, it'll be a close approximation), there is no obvious alternative short of reprimanding people for omitting their unrealized figures... which would be kinda harsh. :stuck_out_tongue: 

**Additional context**

Mock-up of my idea, with a large unrealized loss plotted:

![Screenshot_2023-05-11_03-11-32](https://github.com/freqtrade/frequi/assets/1733537/f4277f32-aa4c-47c6-8239-9439e558bb6d)

And with a small unrealized profit plotted instead:

![Screenshot_2023-05-11_03-11-32a](https://github.com/freqtrade/frequi/assets/1733537/1c8c91cc-5455-4ace-a13f-0c923afdc430)

**Comment by xmatthias** [comment]
Great idea / nice mockup of what you'd like.

Let me know if it works as you hoped.

**Comment by VanessaE** [comment]
It looks good but you left out the "--O-- Unrealized" legend at the top.  Might want to add that.

**Comment by Mandark-droid** [comment]
@xmatthias The Legend from the mockup is not visible in the implemented change it seems. 
![image](https://github.com/freqtrade/frequi/assets/89932595/da17bb0a-23b2-4602-a569-bab9ae48491f)

**Comment by VanessaE** [comment]
On re-checking things, I'm not sure the plot is actually correct.

For example, my graph shows an unrealized loss of about -275, but this disagrees greatly with the figures in the "comparison" table, which has an unrealized loss of about -410.

![Screenshot_2023-05-27_16-02-41](https://github.com/freqtrade/frequi/assets/1733537/0e9da1a9-16ec-4251-b59f-40628adde4f1)
![Screenshot_2023-05-27_16-02-53](https://github.com/freqtrade/frequi/assets/1733537/00213415-ebdc-41ca-a7b2-f6e9f531f490)

A couple of other users report similar inconsistencies:

Here, the user's dashboard shows a large unrealized profit in the figures, but it renders as a small unrealized loss in the graph:

![image](https://github.com/freqtrade/frequi/assets/1733537/aa8c7ef9-a4af-41c1-bf1c-4e7d7d0f4c22)
![image](https://github.com/freqtrade/frequi/assets/1733537/c7099d4a-d520-4c89-a034-56c7559e383e)

And here the user's figures report a larger unrealized loss than the graph shows:

![Screenshot_from_2023-05-27_21-01-13](https://github.com/freqtrade/frequi/assets/1733537/9853401b-15c7-4011-8547-f0075f87ac9b)

What's gone wrong?

**Comment by VanessaE** [comment]
It looks like there's confusion in the displayed profit numbers.  It looks as though the graph is using the "Freqtrade / Open Profit" item -- that is, what would be a single bot's open P/L figure, rather than the "**Summary** / Open Profit" item.

I used to have multiple bots running, but only one bot these days, so it doesn't surprise me that the two sets of figures are different.  Still, it seems to be using the wrong figure. :smiley:

**Comment by Mandark-droid** [comment]
Something is not right here as there is no change in the open/closed profits but its still showing different color on refresh of the dashboard. @xmatthias  Please look into this.
![image](https://github.com/freqtrade/frequi/assets/89932595/7448cecb-cedc-4ad8-8d3c-c45f0b7df478)
![image](https://github.com/freqtrade/frequi/assets/89932595/8c933a80-9af0-4224-b284-88577b793949)
![image](https://github.com/freqtrade/frequi/assets/89932595/2160997e-d582-42db-a1ff-6f4087a35256)
![image](https://github.com/freqtrade/frequi/assets/89932595/bf4bc52f-c297-4634-9164-a3d69ccaf86a)

**Comment by Mandark-droid** [comment]
Seems on every page refresh its plotting it for a different bot. And if you notice for one of the bot its not even showing anything in the unrealized since there are not open
![image](https://github.com/freqtrade/frequi/assets/89932595/e335b6fb-a24b-49b6-a80e-f9edaf6bde50)
![image](https://github.com/freqtrade/frequi/assets/89932595/98707c74-9d47-4aac-a2a0-21086a4f96a2)
![image](https://github.com/freqtrade/frequi/assets/89932595/cc806ee7-1c38-4337-bc5e-f3889c828e76)

**Comment by VanessaE** [comment]
So to summarize, the new unrealized P/L line is probably correct, since it seems to match the actual total of all the user's bots if you add them up by hand, but it shines a light on a couple of other issues, which I'll file separately.
