### ISSUE TITLE
It is recommended that the encoding of the source code be adjusted to utf-8 no-bom (LF).

### ISSUE THREAD

**Issue by webees** [freqtrade/frequi#1264]
**Is your feature request related to a problem? Please describe.**

# This is a minor issue, except that ASCII CRLF gives me a bit of a mess.

**Describe the solution you'd like**

# The source code be adjusted to utf-8 no-bom (LF)

**Describe alternatives you've considered**

🐝

**Additional context**

🐝

**Comment by xmatthias** [comment]
not sure i understand this - if you find a file that's not in "lf" format we can surely change that - but ad hock, i wouln't have found any.
