### ISSUE TITLE
Unable to connect to FreqUI

### ISSUE THREAD

**Issue by beachboy88** [freqtrade/frequi#1280]
Followed the Windows Docker-based installation instructions at https://www.freqtrade.io/en/stable/docker_quickstart/. 

In my browser, when I navigate to http://127.0.0.1:8080/api/v1/, all it says is {"detail":"Not Found"}. No UI, nothing else on the page.

My config file:

{
    "max_open_trades": 3,
    "stake_currency": "USDT",
    "stake_amount": "unlimited",
    "tradable_balance_ratio": 0.99,
    "fiat_display_currency": "USD",
    "dry_run": true,
    "dry_run_wallet": 1000,
    "cancel_open_orders_on_exit": false,
    "trading_mode": "spot",
    "margin_mode": "",
    "unfilledtimeout": {
        "entry": 10,
        "exit": 10,
        "exit_timeout_count": 0,
        "unit": "minutes"
    },
    "entry_pricing": {
        "price_side": "same",
        "use_order_book": true,
        "order_book_top": 1,
        "price_last_balance": 0.0,
        "check_depth_of_market": {
            "enabled": false,
            "bids_to_ask_delta": 1
        }
    },
    "exit_pricing":{
        "price_side": "same",
        "use_order_book": true,
        "order_book_top": 1
    },
    "download_trades": true,
    "exchange": {
        "name": "kraken",
        "key": "",
        "secret": "",
        "ccxt_config": {"enableRateLimit": true},
        "ccxt_async_config": {
            "enableRateLimit": true,
            "rateLimit": 1000
            // Enable the below for downoading data.
            //"rateLimit": 3100
        },
        "pair_whitelist": [
        ],
        "pair_blacklist": [

        ]
    },
    "pairlists": [
        {
            "method": "VolumePairList",
            "number_assets": 20,
            "sort_key": "quoteVolume",
            "min_value": 0,
            "refresh_period": 1800
        }
    ],
    "telegram": {
        "enabled": false,
        "token": "",
        "chat_id": ""
    },
    "api_server": {
        "enabled": true,
        "listen_ip_address": "0.0.0.0",
        "listen_port": 8080,
        "verbosity": "error",
        "enable_openapi": false,
        "jwt_secret_key": "***",
        "ws_token": "***",
        "CORS_origins": [],
        "username": "***",
        "password": "***"
    },
    "bot_name": "freqtrade",
    "initial_state": "running",
    "force_entry_enable": false,
    "internals": {
        "process_throttle_secs": 5
    }
}

**Comment by xmatthias** [comment]
That would sound about right - the correct test url would be  http://127.0.0.1:8080/api/v1/ping - and the UI will be at  http://127.0.0.1:8080/ (without /api/...).
