### ISSUE TITLE
"Cumulative Profit" graph doesn't show all bots' data consistently

### ISSUE THREAD

**Issue by VanessaE** [freqtrade/frequi#1282]
**Describe the bug**

This bug report comes from @Mandark-droid; the images below are his, not mine.  

If the user has more than one bot running, the "Cumulative profit" graph may sometimes only plot the data from one of those bots, rather than all of them consistently, but which bot it picks seems to be random.

Here are three screenshots of the graph taken during the same session, refreshing the page each time:

![241429372-cc806ee7-1c38-4337-bc5e-f3889c828e76](https://github.com/freqtrade/frequi/assets/1733537/78d4af50-4c20-4205-8492-d5e45c7c08a6)
![241429363-98707c74-9d47-4aac-a2a0-21086a4f96a2](https://github.com/freqtrade/frequi/assets/1733537/77d34b7e-bddb-458e-923a-75649e0ff42c)
![241429350-e335b6fb-a24b-49b6-a80e-f9edaf6bde50](https://github.com/freqtrade/frequi/assets/1733537/557bcace-738a-4372-95ca-4b9812502c22)

Since this is random and inconsistent, it doesn't seem logical to include a "steps to reproduce" section.  I guess just try running two or more bots for a while? :smiley:

**Comment by xmatthias** [comment]
for performance reasons, this chart is throttled to refresh only once per minute.
Without that, it'd refresh/redraw every 5 seconds if there's open trades (the frequency that open trades are updated).

If you change the bot comparison selection (or reload the page) - you'll therefore need to wait for up to 1 minute for the graph to be uptodate.
you can force this refresh by going to a different page within the bot (logs/trade/...) - and then returning to the dashboard.

I've tried to improve behavior in this by not throttling the closed trades - but i suspect it can still be flaky if you have one bot without closed trade in your bot list, while trying to change the selection of "bots to show".
