### ISSUE TITLE
Force entry function implementation

### ISSUE THREAD

**Issue by versedpro** [freqtrade/frequi#1324]
**Is your feature request related to a problem? Please describe.**
No it's not a problem but it might be a lack of UI. 

**Describe the solution you'd like**
Force entry functionality will work(mentioned in doc very well) in case of REST API and telegram bot both. However, the users aren't able to call this api endpoint from UI. Instead, they might use swagger doc, but it would be better if you provider this functionality somewhere on UI.

**Describe alternatives you've considered**
I don't have any alternatives right now.

**Additional context**
no additional context. just consider my primary request.

**Comment by xmatthias** [comment]
Force entry must be enabled explicitly in the backend, and is then available in the right-most button in the UI.

If force-entry (setting `force_entry_enable` in the config) is not explicitly set to true, this button will not be shown.

![image](https://github.com/freqtrade/frequi/assets/5024695/f9b08a3e-3d95-4ef7-a387-124e713ece77)
