### ISSUE TITLE
Trade labels not rotating correctly

### ISSUE THREAD

**Issue by vaidab** [freqtrade/frequi#1352]
## Describe your environment

freqtradeorg/freqtrade -> develop_plot docker image
Operating system: Ubuntu 5.4.0
Python Version: 3.11.4
CCXT version: 3.1.44
Freqtrade Version: freqtrade docker-2023.6.dev-a90b7c0b

## Describe the enhancement

The entry icon and probably others in webUI ar tiny! (smaller than the candle's lateral dimension).
Would recommend to increase their size as in the latest image, so they can be quickly seen in the graph.
I provided a TradingView strategy image as a reference to an adequate size.

<img width="256" alt="Screenshot 2023-07-09 at 12 51 20" src="https://github.com/freqtrade/freqtrade/assets/19855026/9fe867f5-c65b-4a4b-964f-286d8c31ce6a">
<img width="190" alt="Screenshot 2023-07-09 at 12 51 37" src="https://github.com/freqtrade/freqtrade/assets/19855026/277d5b5b-013a-4a66-b837-05dd1740febc">
<img width="431" alt="Screenshot 2023-07-09 at 12 51 45" src="https://github.com/freqtrade/freqtrade/assets/19855026/c9b5c2ea-3c31-4347-aa5d-a4a06c61ce77">
<img width="257" alt="Screenshot 2023-07-09 at 12 52 19" src="https://github.com/freqtrade/freqtrade/assets/19855026/f4a119d0-4258-4a32-8884-ca78fd1dc37f">
<img width="401" alt="Screenshot 2023-07-09 at 12 53 42" src="https://github.com/freqtrade/freqtrade/assets/19855026/e909050a-1ebd-44a1-b96f-8f2a8537eac0">

**Comment by vaidab** [comment]
Font size is 100%
Zoom size is 100%
Browser is Safari 16.5.1 (latest version).
Maybe it's a browser incompatibility thing?

**Comment by xmatthias** [comment]
I think your top right image is at the correct size - at least it appears to be.

![image](https://github.com/freqtrade/frequi/assets/5024695/401bfa0a-6484-4180-a4cf-1d561ea07e63)

As mentioned above - the icons don't resize as you zoom in (intentionally) - so if you're at insane zoom levels (where you'll only have a few candles visible) - the icons will show up small - leaving space for what's actually interesting at that level - which is usually the indicators.

**Comment by vaidab** [comment]
It was obtained by playing with the zoom inside the chart (not the browser zoom).
I was thinking, maybe it's because I have a bigger screen...
You can close it if you want, I would prefer it to be visible when I have an overview because that word: "Long" is definitely not visible on the chart. It's a bit hard for me to pinpoint what's happening unless I zoom in a lot (via the mouse scroll / chart zoom in feature).

**Comment by xmatthias** [comment]
i see what you mean with the "long" label ...
but i think the label is the one at fault, not the size of the icon.

What i don't understand (and what the difference is) is that the lable is not rotated (it's therefore covering the actual symbol).
this could very well be a browser issue - would you mind trying this with chrome (or any chromium based browser?)

**Comment by vaidab** [comment]
This one is from Chrome.
<img width="781" alt="Screenshot 2023-07-09 at 14 23 42" src="https://github.com/freqtrade/frequi/assets/19855026/c90ebec9-186e-4fd8-bf4c-fad6f4ac62f8">

**Comment by xmatthias** [comment]
interesting, i still don't understand why it doesn't work - but i'll publish a new version where this is fixed.
