### ISSUE TITLE
Add notes to backtest

### ISSUE THREAD

**Issue by vaidab** [freqtrade/frequi#1353]
**Is your feature request related to a problem? Please describe.**
When testing a strategy and you go to Load Results you have a list of backtests that don't tell you anything about what you did there. Thus, more often than not, you forget some modifications you've done, do them again and re-run the backtest.

**Describe the solution you'd like**
I'd love to be able to add notes to the list of backtests. Sample notes would be:

- timeframe info
- modified strategy to exit in a different way
- best results backtest

**Describe alternatives you've considered**
An alternative would be being able to rename the backtest name/file to something more descriptive.

**Additional context**
<img width="1249" alt="Screenshot 2023-07-09 at 20 06 45" src="https://github.com/freqtrade/frequi/assets/19855026/156fd742-a57c-48b6-8c2f-66fdb48c05de">

**Comment by xmatthias** [comment]
while i can see some small usefulness in it - i don't think it'd provide enough benefit to justify the complexity this would bring.

the whole "load results" screen is loaded from the backtesting directory - using the ".metadata" files as reference.
having more info (like timeframe) would require to load the full backtest result files - which would slow down this view quite some (there's quite a difference between loading a 100 byte json file vs. a potentially several kb file - and that for 100ds of files).

this "file-based database" of backtesting resuts also makes it difficult to add actual notes later on - as it would mean writing these files - which i see as static / imutable.

What you can do is change the name of the file when backtesting via commandline with `--export-filename=user_data/backtest_results/backtest_today.json` - but that'd obviously require you to always name it accordinly beforehand - which is unrealistic if we're honest (you'll usually only care if it had good results).


I'll leave this open as "low prio" for the moment, so eventually someone can pick this up if he has some ideas, but don't expect any activity anytime soon.

**Comment by batcandoi27** [comment]
> while i can see some small usefulness in it - i don't think it'd provide enough benefit to justify the complexity this would bring.
> 
> the whole "load results" screen is loaded from the backtesting directory - using the ".metadata" files as reference. having more info (like timeframe) would require to load the full backtest result files - which would slow down this view quite some (there's quite a difference between loading a 100 byte json file vs. a potentially several kb file - and that for 100ds of files).
> 
> this "file-based database" of backtesting resuts also makes it difficult to add actual notes later on - as it would mean writing these files - which i see as static / imutable.
> 
> What you can do is change the name of the file when backtesting via commandline with `--export-filename=user_data/backtest_results/backtest_today.json` - but that'd obviously require you to always name it accordinly beforehand - which is unrealistic if we're honest (you'll usually only care if it had good results).
> 
> I'll leave this open as "low prio" for the moment, so eventually someone can pick this up if he has some ideas, but don't expect any activity anytime soon.

My opinion is that this problem is very necessary to capture and distinguish different results between backtests! because it's really hard to just see its name and time. The problem with implementation I think can be done by adding an option like : add backtest annotation, then exporting it a separate file with the same name (adding a symbol at the end or with a different extension) and saving it in less than 10 lines including basic and necessary information: time range, timeframe, avg profit, dd, profit fact . v. . Obviously storing and retrieving information in a separate file (very few bytes) is possible!

**Comment by vaidab** [comment]
I find myself rerunning backtests because I don't know which file was used for a specific situarion or continuously loading backtests files in the UI to find the timeframe/time range combo. 
I also have benchmarks (5 min with 1 min detail) that I have noted in notes because I don't want to lose track of them.
For me this feature would be very helpful.
