### ISSUE TITLE
FreqUI chart issues

### ISSUE THREAD

**Issue by RuiSiang** [freqtrade/frequi#1364]
**Describe the bug**
FreqUI chart takes a long time to load and then shows buy and sell signals on every candle.

**To Reproduce**
1. Go to chart
2. Continues loading for about a minute
3. Shows chart with buy and sell signals on every candle

**Expected behavior**
The chart showing normally with buy and sells indicated clearly.

**Screenshots**
![image](https://github.com/freqtrade/frequi/assets/49300088/47795fe6-719f-47a0-aa29-e8af62f12e38)
![image](https://github.com/freqtrade/frequi/assets/49300088/64b791b2-b264-490b-8805-ce5d4f5157e8)
![image](https://github.com/freqtrade/frequi/assets/49300088/f7110f52-db1e-4363-99cd-0122f2b1b7d2)

**Desktop (please complete the following information):**
 - OS: Ubuntu (server), Win10 (client)
 - Browser Chrome
 - Version: docker image freqtradeorg/freqtrade:stable_freqai

**Additional context**
It's not an issue with websocket since I made sure the socket connection passes through.

**Comment by RuiSiang** [comment]
config.json for api_server part
``` json
"api_server": {
    "enabled": true,
    "listen_ip_address": "0.0.0.0",
    "listen_port": 8080,
    "verbosity": "error",
    "enable_openapi": false,
    "jwt_secret_key": "****",
    "ws_token": "****",
    "CORS_origins": [],
    "username": "****",
    "password": "****"
  }
```

**Comment by xmatthias** [comment]
FreqUI takes the data from the freqtrade instance running in the background.

If you're seeing 100% buy signals, then that's your strategy that's issuing that.
Now as you have 500 buy signals, and 499 sell signals, there'll still only be one signal that MAY be acted on - but it's a strategy problem, definitely not a freqUI bug.

**Comment by RuiSiang** [comment]
Sure, so just checking, it doesn't have anything to do with the undefined error right?

**Comment by xmatthias** [comment]
not really, no.
We don't use json.parse around plotting - so that's comming from elsewhere (i'd suspect from the actual plot-config which contains invalid values - but that's a suspicion).
Without plot-config, you'd however get a plot without indicators - which would show completely different than what you have.

**Comment by RuiSiang** [comment]
Thank you!
