### ISSUE TITLE
in Backtesting -> Viewing Results clicking on the gear button resets the view when zoomed in

### ISSUE THREAD

**Issue by vaidab** [freqtrade/frequi#1371]
**Describe the bug**
In FreqUI -> Backtesting -> Viewing Results, clicking on the gear button (in order to add another indicator on the graph) automatically zooms out. You would normally want to maintain the view when adding an indicator.

**To Reproduce**
1. FreqUI,, gFreqUI -> Backtesting 
2. Load a backtest
3. Go to Visualize Results
4. Zoom in towards a smaller timerange 
5. Click on the gear button

**Expected behavior**
The screen should stay zoomed on your timerange while you add the new indicators.

**Comment by xmatthias** [comment]
the zooming out is intentional - as a change to the plotconfig forces a full redraw.

I'll have to look if it's simple to keep the zoom level - but most likely, it's not worth the effort - as you'll not be changing the config around at will.

**Comment by xmatthias** [comment]
Not going to implement this - at least not for now.
it's better to be sure that the new chart renders correctly even if elements were removed than preserving zoom when changing the config.

zoom does stay in place in live mode when candles update though - which is where you'll spend 90% of the time (not configuring / reconfiguring plots).
