### ISSUE TITLE
Add winrate in frequi -> backtesting -> analyze result

### ISSUE THREAD

**Issue by vaidab** [freqtrade/frequi#1372]
Currently, under metrics, we see:
Win/Draw/Loss | 4 / 0 / 7
A small modification would help show the winrate:
Win/Draw/Loss | 4 / 0 / 7 (WR: 36.36%)

**Comment by xmatthias** [comment]
This will be added shortly - but it'll require a fully updated freqtrade bot on develop to actually show up.
That'll obviously change with the next release.
