### ISSUE TITLE
FreqUI not loading the entire timerange

### ISSUE THREAD

**Issue by vaidab** [freqtrade/frequi#1379]
**Describe the bug**
FreqUI doesn't show the timerange from the beginning. It should start at 15/07/2021 but it starts at 08/08/2021.
I have --timerange 20210715-20220106 with startup_candle_count = 41

Logs are correct:
Loading data from 2021-06-04 00:00:00 up to 2022-01-06 00:00:00 (216 days) 
Backtesting with data from 2021-07-15 00:00:00 up to 2022-01-06 00:00:00 (175 days)

First trade: 31/7/2023 (taken from backtesting json)
open_date":"2021-07-31 00:00:00+00:00","close_date":"2021-10-24 00:00:00+00:00"

**Screenshots**
![Screenshot_2023-07-21_at_17 45 00](https://github.com/freqtrade/frequi/assets/19855026/62a609cd-f6f3-400c-b798-38082d4bdf81)

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Safari

**Comment by vaidab** [comment]
Can't reproduce in 0.9.5

**Comment by xmatthias** [comment]
> Can't reproduce in 0.9.5

Can't understand this. It's clearly happening - and will be fixed in develop shortly (it's a freqtrade bug that's actually causing this).
