### ISSUE TITLE
FreqUI showing a Long without a nearby green entry arrow

### ISSUE THREAD

**Issue by vaidab** [freqtrade/frequi#1380]
**FreqUI Version**
- Version of freqUI: 0.9.4  (upgraded to 0.9.5 after the first comment)
- version of freqtrade: freqtrade docker-2023.7.dev-9c1fea0e

**Describe the bug**
I'm having difficulties wrapping my head around this situation: why does my strategy issue a long at the beginning of the timerange, when it doesn't have enough candles to check for my conditions

- I have my conditions plotted in FreqUI and they are false at the time of the long,
- The long is at the beginning in each pair if testing multiple pairs
- You can see from the image that the Entry green arrow should be way later (daily timeframe)
- It starts in 10/08/2021 but even when adding the strat to jupyter, the first enter_long == 1 is at 19/09/2021, right after the green arrow (which is correct)
- it contains the tag of my entry signal
If I set my startup_candles_count to 0 it works correctly (though it should use a 40 candle history to match the indicator's history).
The strategy plots breakouts with a 40 candle history and I set the startup candles to that nr when it plotted the long at the beginning.
![Screenshot_2023-07-21_at_11 01 33](https://github.com/freqtrade/frequi/assets/19855026/bab7b6f8-b9fd-4d86-a683-6ba190e6072b)
- hovering around the Long I see no conditions for entry

**Expected behavior**
The first Long should appear in the vicinity of an entry condition (green entry arrow).

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

---

I can see from some details that this is an old version of freqUI. 
The "long" label is rotated in the last version (as it should be) - preventing it from potentially covering the arrow.

**Comment by vaidab** [comment]
I've updated to 0.9.5 and have updated the description to match the template.
Issue persists, unrelated to #1352 . Providing screenshot:

<img width="1938" alt="Screenshot 2023-07-21 at 20 04 52" src="https://github.com/freqtrade/frequi/assets/19855026/09e29ec8-5303-48ee-9b08-7c8fa83a74ed">

**Comment by xmatthias** [comment]
Most likely related / caused by #1379.

Please make sure to give this a test with the very latest freqtrade version (pushed a few seconds ago - if you're using docker it'll still take a bit until it'll be ready).

**Comment by vaidab** [comment]
Using freqtrade docker-2023.7.dev-68741239 (latest image), I can confirm the green entry arrow appeared before the Long. Thank you for the bugfix.

<img width="1927" alt="Screenshot 2023-07-22 at 07 12 17" src="https://github.com/freqtrade/frequi/assets/19855026/0ee1825e-72cf-4205-8659-e687394bc5e5">
