### ISSUE TITLE
Request failed with status code 404: "Strategy not found" not giving an interface error

### ISSUE THREAD

**Issue by vaidab** [freqtrade/frequi#1387]
**FreqUI Version**

- Version of freqUI: 0.9.5
- version of freqtrade: docker-2023.7.dev-68741239

**Describe the bug**
Clicking on the backtest gives Request failed with status code 404: "Strategy not found"
It should give an interface error.

**To Reproduce**
1. Go to Freqtrade UI -> Backtest
2. Create a bug in your strategy that would prevent it from executing (invalid command)
3. Click on a backtesting result that contains that strategy

**Expected behavior**
It should give an error visible to a user of Freq UI without having to inspect the page errors.

**Desktop:**
 - OS: MacOSX
 - Browser Safari 
 - Version 16.5.2

**Comment by xmatthias** [comment]
While this issue is closed, you'll need the very latest freqtrade version to have this actually apply - otherwise it'll just be some generic error messaage.
