### ISSUE TITLE
Differences between server time and Frequi

### ISSUE THREAD

**Issue by mroodschild** [freqtrade/frequi#1390]
**FreqUI Version**

- Version of freqUI: 0.9.4
- version of freqtrade: freqtrade 2023.6
- WSL2
- Docker: 24.0.2

I have a time difference between the server, the computer and the candles projected in Frequi. Is it a bug or do I have to configure something? I checked the documentation but it doesn't say anything about it.

I observe this in the time:

On the server it is 14:08 on 7/28/2023, however on frequi it is 17:00 on 7/28/2023. I should clarify that my time zone is UTC -3, but it doesn't match the minutes anyway.

Thank you so much!

**Comment by xmatthias** [comment]
The only thing that is irrelevant is the server time (unless it's wrong - in which case you'll have problems connecting to the exchange with an api key).

FreqUI can display candles in either the browser's time, or in UTC - both of which you can configure in the settings page.

the "minutes" will depend on your candles - you'll not see a ":08" candle unless you're on 1m timeframe.

**Comment by mroodschild** [comment]
Thank You xMatthias!
