### ISSUE TITLE
In the dashboard page FreqUI show the summary in bitcoin quoted USDT

### ISSUE THREAD

**Issue by macsim26** [freqtrade/frequi#1405]
**FreqUI Version**

- Version of freqUI: 0.9.5 (Available in the top right corner of the UI)
- version of freqtrade: 2023.6 (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)

**Describe the bug**
In the dashboard page FreqUI show the summary in bitcoin but it is quoted USDT and not BTC

**To Reproduce**
1. use a strategy with BTC as quote currency
2. Click on Dashboard
3. The summary indicate a number in bitcoin but it is quoted USDT

**Expected behavior**
I expect the number in bitcoin to be quoted BTC and not USDT

**Screenshots**
![bitcoin quoted USDT](https://github.com/freqtrade/frequi/assets/88237677/e1e23ac5-d99e-42bc-98dc-081bdd058b13)

**Desktop (please complete the following information):**
 - OS: ubuntu 22.04
 - Browser firefox
 - Version 115.0.2 (64 bits)

**Comment by xmatthias** [comment]
i think you might've missunderstood this. Not answering here does not mean it's not a bug.

I'm yet to get to this - so i guess it makes sense to keep this open.

**Comment by macsim26** [comment]
Sorry i have think it was not so important but today with the new update of freqtrade in 2023.08 and freqUI 0.9.7 i have noted that both : 
-the donnut of the balance as desappair in the trade page (see images)
-the  daily profit panel in daily stats too...
Do you want i open a new bug? 
Thanks
![Capture du 2023-09-01 07-55-00](https://github.com/freqtrade/frequi/assets/88237677/b68bbcec-b50a-4113-ab97-041556c7b480)
![Capture du 2023-09-01 07-56-02](https://github.com/freqtrade/frequi/assets/88237677/2f31b5cd-5d95-4d29-8f66-eb5651d8ef95)

**Comment by xmatthias** [comment]
nah, will be fixed soon
