### ISSUE TITLE
rounding values in daily stats

### ISSUE THREAD

**Issue by macsim26** [freqtrade/frequi#1452]
The values shown in daily stats often contain too many digits after the decimal point, shifting the number of trades out of the window.

I'd like the value to be rounded to 10 decimal places, for example.

Here are some screenshots showing this:

![Capture du 2023-09-02 12-10-24](https://github.com/freqtrade/frequi/assets/88237677/54ea45b1-a33f-42d3-89fd-07e38c7b7a02)
![Capture du 2023-09-02 12-12-02](https://github.com/freqtrade/frequi/assets/88237677/097fbc73-c570-43cc-b579-ea7933de5101)

**Comment by macsim26** [comment]
Noob question how do i install this corrected version? Must i install the develop freqtrade branch completely or i can just install this freqUI with the 2023.08 stable freqtrade branch? Thanks you are faster than light...

**Comment by xmatthias** [comment]
it's currently only on the main branch, which means you can't install it.

it'll be available for installation via freqtrade once we do a release.
