### ISSUE TITLE
Chart / Graph Page spings forever

### ISSUE THREAD

**Issue by diamkil** [freqtrade/frequi#1462]
**FreqUI Version**

- Version of freqUI: 0.9.7 (Available in the top right corner of the UI)
- version of freqtrade: 2023.8 (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)

**Describe the bug**
When opening the page labeled "Chart" in freqUI it spins forever.

Console error: 
```runtime-core.esm-bundler.js:226
SyntaxError: "undefined" is not valid JSON
    at JSON.parse (<anonymous>)
    at Ce (deepClone.ts:2:15)
    at Proxy.plotConfigChanged (plotConfig.ts:72:35)
    at Proxy.<anonymous> (pinia.mjs:1375:30)
    at CandleChartContainer.vue:218:3
    at runtime-core.esm-bundler.js:2675:88
    at Ir (runtime-core.esm-bundler.js:158:18)
    at ln (runtime-core.esm-bundler.js:166:17)
    at t.__weh.t.__weh (runtime-core.esm-bundler.js:2655:19)
    at ym (runtime-core.esm-bundler.js:325:40)
```

**To Reproduce**
1. Create a fresh LXC container
2. Follow the install steps
3. Generate config using "freqtrade new-config"
4. Configure the exchange and the StaticPairList
5. Launch "freqtrade webserver"
6. Open the page, navigate to "Chart"
7. Never loads....

**Expected behavior**
The chart loads and works

**Screenshots**
![image](https://github.com/freqtrade/frequi/assets/35732047/c6e8a4ab-95ce-4003-9476-3602f3420951)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 11 22H2 (Build 22621.2134)
 - Browser [e.g. chrome, safari] Chrome and Firefox
 - Version [e.g. 22] Chrome 116.0.5845.180 / Firefox 117.0

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] iPhone 14 Pro Max
 - OS: [e.g. iOS8.1] iOS 17 Beta 8
 - Browser [e.g. stock browser, safari] Safari
 - Version [e.g. 22] -

**Additional context**
-

**Comment by xmatthias** [comment]
Well what should it load with?

You're opening the chart in webserver mode - which means
* there's no strategy
* there's no live running bot

As such - you'll first need to
* define a strategy (screenshot clearly shows that you didn't do that yet
* pick a pair (or leave the one selected)
* pick a timerange you have data for (use `download-data` first)
* depending on the config - pick a timeframe
* click the "refresh" button next to the pair 


If on the other hand, you start the bot in trade mode (`freqtrade trade`) - the chart will load just fine (you'll also find that some options, like selecting a strategy) - are no longer available on the chart page.
