### ISSUE TITLE
Conditional plotting

### ISSUE THREAD

**Issue by fmferrari** [freqtrade/frequi#1618]
**Is your feature request related to a problem? Please describe.**
I need to plot markers whenever a certain condition is met.

**Describe the solution you'd like**
I would like to be able to write a plot_config variable that would let me see the markers that i need to conditionally plot, on freqUI chart. Something like this:

```
    plot_config = {
        'main_plot': {
        },
        'subplots': {
            "MACD": {
                'vwmacd': {'color': 'blue'},
                'vwmacdsignal': {'color': 'orange'},
                'macd_crossover': {
                    'color': 'green',
                    'when': lambda x: x['macd_crossover'] > 0
                },
            }
        }
    }
```

**Describe alternatives you've considered**
Maybe its already implemented, but I could not find it in the documentation.
I also wanted to plot a scatter type charts and wasnt able to do it.

**Comment by xmatthias** [comment]
I'd recommend to use freqUI itself for the configuration.
it's easier and guides you through the process - the output is either a saved freqUI config - or (additionally) a valid configuration for freqtrade.

---

You can pretty easily configure this by doing the conditional calculation in the backend - and assigning a "sane" value to this column (basically the value where you'd like to see the dot.

``` python
        macd = ta.MACD(dataframe)
        dataframe['macd'] = macd['macd']
        dataframe['macdsignal'] = macd['macdsignal']
        dataframe['macdhist'] = macd['macdhist']
        dataframe.loc[
            (qtpylib.crossed(dataframe['macd'], dataframe['macdsignal'])),
            'macd_crossover'] = dataframe['macdsignal']
```

In this case, i choose to plot all points in the subplot - therefore the value assigned is macd_signal (this is obviously optional and can be configured differently).

You then configure the plot in the frontend via the plot-configurator.
the outcomming plot is the following (you can also use this and import it into a (new) freqUI plot config, if you'd like to experiment first.
The value in the strategy can be used, but is by no means a must (this way, you can have multiple configs for the same strategy).


``` json
{
  "main_plot": {},
  "subplots": {
    "MACD": {
      "macd": {
        "color": "#cf8895",
        "type": "line"
      },
      "macdsignal": {
        "color": "#80cee1",
        "type": "line"
      },
      "macdhist": {
        "color": "#307009",
        "type": "bar"
      },
      "macd_crossover": {
        "color": "#32e010",
        "type": "scatter"
      }
    }
  }
}
```


Looks then something like this:

![image](https://github.com/freqtrade/frequi/assets/5024695/cba9e409-e76c-44c3-83de-01af345a8c7b)

**Comment by fmferrari** [comment]
Thanks a lot! worked great
