### ISSUE TITLE
Chart settings appear off-screen in trade mode

### ISSUE THREAD

**Issue by serpent213** [freqtrade/frequi#1636]
**FreqUI Version**
- Version of freqUI: 1.1.1 and main
- version of freqtrade: 2023.11 and develop

**Describe the bug**
Chart settings appear off-screen in trade mode.

**To Reproduce**
1. Go to 'Chart'
2. Click on 'Settings'
3. Menu is barely visible at the right edge of the screen.

**Expected behavior**
Shrinkage of the chart as menu slides in – interestingly this *sometimes* works as expected.

**Screenshots**
<img width="452" alt="Screenshot 2023-12-16 at 21 54 14" src="https://github.com/freqtrade/frequi/assets/106662/ca7a2aec-381c-4c1c-ab5b-6b835b129173">

**Desktop**
 - OS: MacOS
 - Browser Firefox, Safari
 - Version: latest

**Additional context**
Maybe a bug in Vue?

**Comment by xmatthias** [comment]
interesting find - appears to be a bug in firefox's flexbox implementation - where layout changes lead to overflowing the parent div.

It's pretty easily fixed though.

if that works on safari i can't tell - let me know if it doesn't work with the next release.

**Comment by serpent213** [comment]
Gave it a quick spin on *main*, looks fine now!  👍🏻
