### ISSUE TITLE
add a new column "Position Adjs" or "# of Orders" into the tables of "Open Trades" and "Closed Trades"

### ISSUE THREAD

**Issue by abdozoon** [freqtrade/frequi#1678]
I know we could click on each trade and see the number of orders and their details, but it would be neater if we can have a summary column on the tables?

**Comment by xmatthias** [comment]
I actually don't think so, no.

I don't really see what difference (or information benefit) the number of entry/exit orders would make - you've got the amount - given a roughly predictable strategy, that should tell you how many entries were done.

If we were to add an additional column, it'd have to replace another column (obviously depending on screen size - but i'm thinking about a regular 1080p screen now) - but for now, i don't see which column this should replace - as all columns do have their use.

**Comment by abdozoon** [comment]
I think it would provide the same benefit of Telegram already having it in the /status command output, but I believe having it in FreqUI is way more convenient :)

With a bit of adjustment, like shrinking some columns and the current profit rectangles, doing some rounding rate-based columns, wouldn't it be still possible? :)

On a 1080p screen, I played with a photo editor to see if we can fit it in.

![image](https://github.com/freqtrade/frequi/assets/25867871/1c6973bf-45b0-4aaa-b7b1-3af0ddc13462)

**Comment by xmatthias** [comment]
You can't reliably round, as some exchanges don't provide proper precision numbers (kucoin, mainly, but not the only  one) - and you'll have pairs ranging from 40k to 0.0000001 ... so every static round > 10 decimals can lead to 0.0 rates on some shitcoins - but rounding to 10 decimals won't help with column width.

Considering the `/status` command - that should be seen as the trade detail view - where it's available already.

**Comment by abdozoon** [comment]
I agree regarding the rounding part.
Even without it, I think a small column like the "# Orders" can be fitted for the convenience of FreqUI users or having data reported similarly across several tools, as possible.

**Comment by xmatthias** [comment]
i don't see the use of it, sorry.
**If** we can fit more columns in it  - then number of orders is not very high on the list, sorry.

Columns like liquidation price, or total profit would make 10x more sense than "order number".

Aside from that - if you compare the "open orders" table with telegram, then it'd correspond to `/status table` - not to `/status` (which is the detail view for the trades).

**Comment by abdozoon** [comment]
no worries, it's ok.

If you have some time in the next few years and would like to play with the columns, please think about adding the option for the users to customize the visible columns, here everyone will use it according to their needs.

Yes, I was referring to the "/status table", not "/status", it's my mistake.

**Comment by xmatthias** [comment]
> If you have some time in the next few years and would like to play with the columns, please think about adding the option for the users to customize the visible columns, here everyone will use it according to their needs.

Feel free to submit a PR.

I neither think that makes sense, nor will it be easily manageable (from a performance perspective, too). Most every column needs different formatting and special cases - which means every supported column must be manually, explicitly defined.
