### ISSUE TITLE
Hitting "Enter" key in Partial Exit prompt executes two orders

### ISSUE THREAD

**Issue by abdozoon** [freqtrade/frequi#1691]
**FreqUI Version**

- Version of freqUI: 1.1.1
- version of freqtrade: 2023.12 

When hitting the Enter key in the partial exit prompt, FreqUI creates two exit orders instead of one.
Edit: seems to be impacting Market type orders only.

**To Reproduce**
1. Open FreqUI
2. Click on The Forceexit Partial action for any specific trade.
3. I set the order type to Market
4. Hit the enter key on your keyboard.
5. FreqUI creates and execute two orders. 

**Expected behavior**
Only a single partial exit order to be created and executed.

**Screenshots**
![image](https://github.com/freqtrade/frequi/assets/25867871/b9c17f47-73a6-4f41-ba09-d886c0761999)

**Desktop (please complete the following information):**
 - OS: Docker
 - Browser [e.g. chrome, safari]: Firefox
 - Version [e.g. 22]: latest

**Additional context**
I created a new freqtrade docker instance from scratch, on dry-run mode, and can still reproduce the issue.
Using mouse, it's ok, only a single order is created and executed.

**Comment by xmatthias** [comment]
nice catch - will be fixed with the next version.
