### ISSUE TITLE
Organizing indicators in charts by polts

### ISSUE THREAD

**Issue by mohsenjavidpanah** [freqtrade/frequi#1692]
Hi
I have a suggestion for show/hide indicators of charts, top of chart now is noisy :zipper_mouth: when chart contains very number of indicators
My suggestion is:

0. Show PLOTs instead of indicators as a show/hide button
1. Show/Hide A PLOT when user touching/clicking related button
2. Organize every indicators elements by PLOTs and after holding mouse or touching on the button for example more than  2 sec then show indicators that contained in PLOTs
3. Show/Hide sub-indicators of plot when user touching/clicking related sub-items of PLOTs buttons

**Comment by xmatthias** [comment]
i'm not entirely sure what you mean with "hide plot".

the "plot" in my definition is the whole chart - if you hide the whole chart - what would you be seeing then?  the gray background?

Maybe you can describe a bit better what exactly you mean ... ?

**Comment by mohsenjavidpanah** [comment]
Okay, this is an image that describing this suggestion:


![desired_chart](https://github.com/freqtrade/frequi/assets/28291175/85ec1aa4-82f4-438e-a6ec-96fc3926275f)


In my definition a plot is a separate section that define on the chart settings:

![Screenshot from 2024-01-16 07-54-51](https://github.com/freqtrade/frequi/assets/28291175/d5c22259-0be2-45e2-a08f-38d2deaaad19)

The decision of user can determine what plot must show and/or hide, As UI/UX we can set a rule, for controling latest shown plot and disable button to hide this latest plot.

**Comment by xmatthias** [comment]
well essentially, it's a simple grouping of the legend based on subplots - so you'd hide the whole "RSI" section at once.
While that sounds like it would make sense, I do not think that grouping of legends is possible in Apache echarts (the component we're using for charting). at least i couldn't find anything apart from unanswered questions about this topic.

If you think it is possible or have better luck with searching, please provide me with a reference / link to that. 
otherwise, i'll have to close this as not possible since the upstream component doesn't support this.

**Comment by mohsenjavidpanah** [comment]
I create new feature issue for Apache Echarts and suggest to support this feature:

https://github.com/apache/echarts/issues/19515

**Comment by xmatthias** [comment]
Seem like this ain't possible with echarts - so the way you're proposing is not something we'll pursue.


however, what you're aiming for is possible already pretty simply by using multiple plot configurations.

Simply create a "master" one - and one (or a few) duplicates which remove a few indicators (there's a clone button at the otp right).
You can use the combo-box at the top right to switch between configurations - which will even provide you with additional flexibility, as maybe the "reduced2" should show completely different indicators, which are not even part of the initial setup.

![freqUI 2024-01-16 18-06](https://github.com/freqtrade/frequi/assets/5024695/c6c4faf6-a996-4532-b464-1ab6d94b2262)

**Comment by Canx** [comment]
And what about an eye that hides/shows indicators from the indicator list, when an indicator is selected? It could be below the list (near de color selection)

**Comment by xmatthias** [comment]
you can still hide individual indicators by clicking on them.
echarts however doesn't support "legend groups" - so until that's implemened, i don't see any need for us to change anything.
