### ISSUE TITLE
Use scoped only style in vue components

### ISSUE THREAD

**Issue by gaugau3000** [freqtrade/frequi#17]
Hi,

Not use scoped only css/scss in Vuejs component could have side effects on other components.
We can use [deep selectors](https://vue-loader.vuejs.org/guide/scoped-css.html#deep-selectors) when need to propagate to child components (exemple: when we use a bootstrap component)

Have a nice day.

**Comment by xmatthias** [comment]
Yes i agree... 
and we don't typically use non-scoped styles in components (apart from `NavBar.vue` - it would appear) - as i tried to be careful with this as i know about the unintended side-effects of this.

At least i wasn't able to identify another file where non-scoped styles are used.
