### ISSUE TITLE
in the new freqUI the zoom is reinitialised to the full scale at each new candle

### ISSUE THREAD

**Issue by macsim26** [freqtrade/frequi#1742]
**FreqUI Version**

- Version of freqUI: _____ 1.2.3
- version of freqtrade: _____2024.2-dev-9e89567ee
**Describe the bug**
Hello with the new version of FreqUI the zoom is reinitialised to the full scale at each new candle.
The bug appeared when I updated my live BOT with the stable version so i tried the dev version on another VPS and it's the same.

**Expected behavior**
I loved when the zoom remain the same all the time...

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser Firefox
 - Version 122.0
Is there a way to force the install of the older version of FreqUI?
Thanks a lot.
Miguel

**Comment by xmatthias** [comment]
well you can always use `freqtrade install-ui --ui-version <version>` to get an older version.
can't guarantee that an older version works with a newer freqtrade version without a problem though.

I'd not know what broke this (reverting recent changes doesn't make it behave differently) - hence i'm not entirely sure if this ever worked the way you think it did.
in the end, the whole dataset is swapped - which i guess will trigger a full re-draw of the chart.

Best let me know with which version it's working for you.

**Comment by xmatthias** [comment]
nevermind - found it ... will be fixed in main / with the next release.
