### ISSUE TITLE
Cumulative Profit Chart is broken

### ISSUE THREAD

**Issue by wassertim** [freqtrade/frequi#1770]
**FreqUI Version**

- Version of freqUI: latest
- version of freqtrade: NA

**Describe the bug**
As a user of frequi, I recently noticed, that the cumulative profit chart has gone broken. When you select a bot, it does not change and behaves strangely, not showing the actual performance of a selected bot. 

I also found the cause. The last commit to the CumProfitChart is changing some typings and also property names from noMerge to notMerge. And that seems is breaking the feature.

```typescript
chart.value?.setOption(chartOptionsLoc, { notMerge: true });
```
Here is the link to the commit:
https://github.com/freqtrade/frequi/commit/304e0ac98fc560ebdef26cf120cdbf336ab09005

**To Reproduce**
1. checkout main branch
2. run it locally with your trading bots
3. select one of your bots
4. See the cumulative chart

**Expected behavior**
The cumulative chart should show a performance of a bot after selecting it.

**Screenshots**
<img width="1471" alt="Screenshot 2024-02-26 at 09 57 08" src="https://github.com/freqtrade/frequi/assets/227707/3bf82d1a-05ec-4639-b197-69c86fcf8f07">

**Desktop (please complete the following information):**
 - OS: NA
 - Browser every browser
 - Version NA

**Smartphone (please complete the following information):**
 - Device: NA
 - OS: NA
 - Browser NA
 - Version NA

**Additional context**
By reverting [that](https://github.com/freqtrade/frequi/commit/304e0ac98fc560ebdef26cf120cdbf336ab09005) commit, the issue can be fixed quickly. Should I create a PR?

**Comment by xmatthias** [comment]
Well the fun part is - the "noMerge" property was a spelling mistake (ported from other charts) - and never had any actual impact (as far as i could find, `noMerge` never existed on echarts).

Removing that line will be fine (see linked commit) - reverting the whole commit is not - as this does now provide some additional type-safety - allowing typescript to catch such mistakes (like - spelling mistakes).
