### ISSUE TITLE
CHANGE LOGO TO BENDER

### ISSUE THREAD

**Issue by keithorange** [freqtrade/frequi#1783]
![BotsSyp4](https://github.com/freqtrade/frequi/assets/130861337/69014556-8bdc-4740-b6ee-c47aecf99ff0)
![bender-money](https://github.com/freqtrade/frequi/assets/130861337/88214547-da58-4880-9f3b-9458caca2c32)

**Comment by xmatthias** [comment]
well - no - but thanks for the suggestion.
