### ISSUE TITLE
wanna delete UI trade history.

### ISSUE THREAD

**Issue by shio2345** [freqtrade/frequi#1784]
**FreqUI Version**

- Version of freqUI: 1.2.5
- version of freqtrade: freqtrade 2023.9-dev

As the title suggests, I would like to delete my UI trade history in order to change the account I operate.
If this operation is possible, please let me know how to do it.
Sorry if this is mentioned in the documentation or previous questions.

**Comment by xmatthias** [comment]
from the UI, you can delete individual open trades - but not closed ones (and i also don't really see us adding this at the moment - as i fail to see the use).

If you're trying to change account - you'll usually want to delete all trades, in which case i'd instead suggest to start with a fresh database - which you can do by simply changing the [database url](https://www.freqtrade.io/en/latest/bot-usage/#how-to-use-db-url) (or via the `db_url` config option) when starting the bot (or by deleting the database files).

**Comment by shio2345** [comment]
Thank you for your response!
I would like to delete the database.
How can I delete it?

**Comment by xmatthias** [comment]
assuming you're using a default setup - it's most likely something around `rm user_data/tradesv3.dry_run.sqlite*`.

Now the actual path and name may vary depending how you did start the bot - but searching for `.sqlite` should give you your database file. You should also make sure to delete files like `*.sqlite-wal` (and consorts) - to make sure the database is properly reset.
