### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by mouhamed-o** [freqtrade/frequi#179]
**Describe the bug**
I can't login 

**Screenshots**
vue-router.esm.js:2008 Uncaught (in promise) Error: Redirected when going from "/login?redirect=%2Fdashboard" to "/dashboard" via a navigation guard.
    at Gt (vue-router.esm.js:2008)
    at Mt (vue-router.esm.js:1967)
    at vue-router.esm.js:2314
    at index.ts:74
    at h (vue-router.esm.js:2300)
    at r (vue-router.esm.js:1947)
    at r (vue-router.esm.js:1951)
    at Rt (vue-router.esm.js:1955)
    at ee.confirmTransition (vue-router.esm.js:2330)
    at ee.transitionTo (vue-router.esm.js:2203)

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04
 - Browser I test with all browser
 - Version Latest

**Comment by xmatthias** [comment]
i'm quite tempted to simply close this issue as it includes no information whatsoever. Not what you're trying to do other than "can't login".


The way frequi works is it requires a running freqtrade bot with API enabled someplace. 
You need to be able to connect to this API from your system directly - and you need to use that URL when logging in.

If this URL is wrong, or freqtrade is misconfigured, frequi will show you that there was a problem logging you in. 
It's then up to the user to figure out if username, password, or the URL is wrong - as this is almost impossible to determine automatically.
it's also possible that the bot is not configured with the API exposed, or that CORS is not setup correctly.

**Comment by xmatthias** [comment]
This should be closed now with 82cf57a - which will now link you to the documentation according to the error received.
