### ISSUE TITLE
INSTANTLY CONNECT TO ALL BOTS! Why do we have to TYPE IN the URL every time WTF!

### ISSUE THREAD

**Issue by keithorange** [freqtrade/frequi#1821]
I am very frustrated having to type in the URL of my parallel bots into ONE frequi page so i can monitor them all at once. Instead, this should be automated and done easily through a file or something! Why are we having to MANUALLY SETUP OUR BOTS EVERYTIME!!!!!

This is not in the tutorial or guides, if it is a feature its obscure. Help me find it or I will write it!!!

**Comment by stash86** [comment]
You should learn proper manner on writing in public space. If you think you can write it, please do. We will wait for the PR

**Comment by keithorange** [comment]
You should write proper code!

**Comment by xmatthias** [comment]
@keithorange Your behavior with this Organization will change. 
I'll not tolerate abuse in this organization.

Please consider this as your **last warning** (you've been told several times before in the main freqtrade repository).

One more such behavior, and you'll be the first to be blocked / banned from interacting with this github organization.
Thanks for your understanding.
