### ISSUE TITLE
Public IP Instance possible?

### ISSUE THREAD

**Issue by Immortality-IMT** [freqtrade/frequi#1918]
A secure public instance of freqtrade ui, so that it is publically viewable from a public ip. For fun.

I can disable the features in the ui to make it readonly, but utlizing the browser storage for holding passwords is too hard to workaround. 

Is it possible?

I currently have to inject the strategy programmatically to some success into the index js file with...
```
// Strategy 1  
const botId1 = 'ftbot.1';
const auth1 = new Un(botId1);
const loginData1 = {
  botName: 'Strategy1',
  url: 'http://127.0.0.1:8080',
  username: 'freqtrader',
  password: 'xxxx'
};

auth1.login(loginData1)
  .then(() => {
    console.log('Login successful for Strategy1');
    // Ensure tokens are stored
    console.log('Access Token:', auth1.getAccessToken());
    console.log('Refresh Token:', auth1.getRefreshToken());

    console.log('Set Token:', auth1.setAccessToken());
    // Continue with further operations after login
  })
  .catch((error) => {
    console.error('Login failed for Strategy1:', error);
    // Handle login error for Strategy1
  });  
```
The issue is that the js source code and password make anyone be able to mess with the bot. I would need to add the bot to the webui, server side. What hook in is there to achieve that?

The ui must be grabbing server side data in some event that could also grab the strategy configs info and configure the ui with it.

Any help appreciated

**Comment by stash86** [comment]
frequi never meant to be opened to public.

If you want to do so, it's better to just create your own dashboard and use API call to get the data from the bot (which is what frequi also doing).

**Comment by Immortality-IMT** [comment]
" just create your own dashboard " How long do think fequi takes to program? I would rather modify the open source frequi to perform that task if possible. It's many months of programming.

**Comment by stash86** [comment]
well, you are free to fork and modify frequi if you think it's faster/easier than to create a dashboard from scratch.

Just for reference, it took me less than a month to create the initial version of my own dashboard from scratch on PHP. It's simple and not come close to frequi, but it's doing what I want, a read-only dashboard to show my bots to public in safe way.

To answer your question, if you want to embed the login info in safe way, you need server side processing, which is what PHP and Node.JS provide. VueJS (from what I know) is client-side, so there is no way to store your login info securely, as you have mentioned above

**Comment by xmatthias** [comment]
Neither FreqUI, nor the freqtrade API (which is required to get the data) are meant to be exposed to the public internet.
We clearly state this in the [documentation](https://www.freqtrade.io/en/stable/rest-api/):

> We strongly recommend to not expose this API to the internet and choose a strong, unique password, since others will potentially be able to control your bot.

Freqtrade (as well as freqUI) targets private users working on their strategies - hence there is no need for advanced permission control, like read only users.

A "public dashboard" - or "multiple users" sounds like an enterprise feature - something you'd need to sell freqtrade to users - but not for your own usage.
I see no good reason to provide such functionality for your own, personal trading.

As such, features aimed at commercial usecases is not something we'll be facilitating as part of our free, voluntary, open source work.

As such, please understand that this is not something we'll be working on or provide assistance with.

**Comment by Immortality-IMT** [comment]
I would like to share my work on the subject, should someone want to try. However insecure, the questions has been asked previously. 

Delete these API calls in the rpc python files...

/start Starts the trader.
/stop Stops the trader.
/stopbuy Stops the trader from opening new trades. Gracefully closes open trades according to their rules.
/reload_config Reloads the configuration file.
/delete_trade <trade_id> Remove trade from the database. Tries to close open orders. Requires manual handling of this trade on the exchange.
/show_config Shows part of the current configuration with relevant settings to operation.
/logs Shows last log messages.
/forcesell <trade_id> Instantly sells the given trade (Ignoring minimum_roi).
/forcesell all Instantly sells all open trades (Ignoring minimum_roi).
/forcebuy <pair> [rate](https://imt.cx/kb.php?page=rate&action=edit) Instantly buys the given pair. Rate is optional. (forcebuy_enable must be set to True)

Edit api_auth.py and hardcode the username and password in the py file which is not then in javascript. Any username and password would then work.

Add the strategy programmically by editing frequi source code...
```
// Strategy 1  
const botId1 = 'ftbot.1';
const auth1 = new Un(botId1);
const loginData1 = {
  botName: 'Strategy1',
  url: 'http://127.0.0.1:8080',
  username: 'freqtrader',
  password: 'xxxx'
};

auth1.login(loginData1)
  .then(() => {
    console.log('Login successful for Strategy1');
    // Ensure tokens are stored
    console.log('Access Token:', auth1.getAccessToken());
    console.log('Refresh Token:', auth1.getRefreshToken());

    console.log('Set Token:', auth1.setAccessToken());
    // Continue with further operations after login
  })
  .catch((error) => {
    console.error('Login failed for Strategy1:', error);
    // Handle login error for Strategy1
  });
```
Delete any sensitive functions from frequi source code such as the login, logout, and bot control function until it is essentially read only.

**Comment by xmatthias** [comment]
I've edited your post above to remove the description.

I'd prefer to not have an instruction on "how to get hacked easily" on our repositories, hence i'll ask you not to share this again in our channels (github, discord, ...).

While you're free in doing so - it's not safe - and random people finding this will not be able to determine this eventually, and just think "oh great, letme use this".
Also, performing such modifications will result in a modified (and hence, unsupported) bot.

Thanks for your understanding and following of this in the future.
