### ISSUE TITLE
Make backtest more visible and user friendly from the UI

### ISSUE THREAD

**Issue by haxwell** [freqtrade/frequi#1967]
**Is your feature request related to a problem? Please describe.**
Yes. In trying to get backtest mode running, I didn't realize that the code was looking for data in the ft_userdata/user_data/data/[exchange_name] directory. Of course, reading the documentation did answer that question, but that puts the onus on the user, rather than on the app.

**Describe the solution you'd like**
I would like to be able to select backtest mode from the UI, and if there is a requirement before backtest is usable, the app should explain (perhaps by an alert dialog, or a distinct page), "Hey, you need to download some data first. This is how you do it....". In a more complete solution, the user would select backtest, there would be a UI for downloading that data, after which it would direct the user to the backtest page.

**Describe alternatives you've considered**
I can't think of any better paths to a resolution than the general solution I have described above.

**Additional context**
 -

**Comment by xmatthias** [comment]
Backtesting will be available when freqtrade is started in [webserver mode](https://www.freqtrade.io/en/latest/freq-ui/#backtesting).

It's pointless (and confusing) to show it in any other mode - as it would suggest functionality that simply is not working 90% of the time (assuming you'll be looking at a live bot most of the time) - so you have a button you see all the time - but cannot click - for no good reason other than "i'm too lazy to read the docs".

As you're correctly pointing out - reading the documentation does help - so  that's what i'll recommend you to do.
Please read the documentation - we recommend to at least fly over the docs from top to bottom at least once - to get to know what functionality freqtrade offers and what the limitations are.

**Comment by haxwell** [comment]
@xmatthias Thanks for taking the time to write such a detailed reply, describing your thinking. I appreciate it, and I understand where you are coming from. :pray:
