### ISSUE TITLE
possibility to change color of subplot indicator based on value or range

### ISSUE THREAD

**Issue by denisdemaisbr** [freqtrade/frequi#2019]
A way to change color of subplot based on range/value

if MACD > 0:
  color = green

if MACD == 0:
  color = white

if MACD < 0:
  color = red

**Comment by xmatthias** [comment]
well echarts would support this through visualMap (kindof) - but i'm not sure that we can provide an interface (how to configure this via UI) flexible enough to make it useful beyond some **very** basic cases (comparisons to static numbers, essentially).

comparisons to static numbers (eq, lt, gt) might be rather simple.

but what would provide actual benefit is  "change color if EMA20 > ema50" (for example) - which i currently don't see supported in echarts (at least i couldn't find how to do that) - and which makes the feature actually pretty much pointless, as most indicators are not bound.

**Comment by froggleston** [comment]
You could have three columns in your dataframe, each corresponding to each of those conditions, e.g. MACD_above_0, MACD_is_0, MACD_below_0. You could then add three line plots to the same subplot and colour them accordingly.

**Comment by denisdemaisbr** [comment]
nice; 
I'm study python to can contribute more then ask!
