### ISSUE TITLE
manual form like binance 'buy/sell' on limit spot

### ISSUE THREAD

**Issue by denisdemaisbr** [freqtrade/frequi#2030]
**Is your feature request related to a problem? Please describe.**
A new form to replicate a manual entry limit on spot to buy/sell

**Describe the solution you'd like**
standart CEX form (I know enter manual, but, it some confuse)

**Describe alternatives you've considered**
a standart CEX from is a market way to bring new users =)

**Additional context**
some time a manual trade can be nice

**Comment by xmatthias** [comment]
by default, freqtrade prevents this kind of behavior - as it's contrary to using strategy trading - and manual intervention will mostly automatically void your strategy's backtest.

You can however easily enable this via [`force_entry_enable`](https://www.freqtrade.io/en/stable/configuration/#understand-force_entry_enable) - which will give you a new button in the bot controls - and will allow manual entries.

These trades will then be entered (according to what you provide) - and will then be executed based on the regular strategy rules.
