### ISSUE TITLE
frequi dont show lastest candles (2024.7.1)

### ISSUE THREAD

**Issue by denisdemaisbr** [freqtrade/frequi#2041]
**FreqUI Version**

- Version of freqUI: V: 1.4.0-e627395
- version of freqtrade: 2024.7.1

**Describe the bug**
frequi dont show 'lastest' candles

**To Reproduce**

**Expected behavior**
show lastest candles

**Screenshots**

![image](https://github.com/user-attachments/assets/f7145f92-281f-4b31-9e60-cb6e3bf255e8)

**Desktop (please complete the following information):**
 - OS: windows 10 pro
 - Browser chrome
 - Version 128.0.6613.84 (Compilação oficial) (64 bits)

**Smartphone (please complete the following information):**

**Additional context**
freqtrade running ubuntu 20.x
timedatectl set-timezone America/Sao_Paulo
frequi w/ America/Sao_Paulo

**Comment by stash86** [comment]
Frequi won't show open candle. The latest candle you expecting were still open
