### ISSUE TITLE
Error while building with docker-compose

### ISSUE THREAD

**Issue by yusufiga** [freqtrade/frequi#205]
**Describe the bug**
I got following error when I'm running docker-compose build. I don't have any network connection problem on my raspberry pi

```
info There appears to be trouble with your network connection. Retrying...
info If you think this is a bug, please open a bug report with the information provided in "/app/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
error An unexpected error occurred: "https://registry.yarnpkg.com/vue-material-design-icons/-/vue-material-design-icons-4.11.0.tgz: ESOCKETTIMEDOUT".
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
ERROR: Service 'frequi' failed to build : The command '/bin/sh -c yarn' returned a non-zero code: 1
```

**To Reproduce**
run docker-compose build from terminal

**Expected behavior**
It should build without any issue

**Desktop :**
 - OS: Raspian
 - Version: Buster

**Comment by xmatthias** [comment]
This is not a frequi bug. The logs indicate one of the following (not necessarily in this order):

* yarn bug (please report to yarn)
* downtime of yarnpkg.com (please retry again)
* Your docker-networking is messed up (fix that and try again).

Neither of these options are a problem of frequi.

**Comment by xmatthias** [comment]
based on a quick google search i found https://stackoverflow.com/questions/55845756/esockettimedout-error-while-yarn-install-command

I think it'll appear if you have a slow internet connection (or a shitty SD card with low write speeds).
i don't think it's necessary to add this setting to the common dockerfile though.
