### ISSUE TITLE
Pairlist-config in Webserver mode does not work (likely since ccxt moved the columns around)

### ISSUE THREAD

**Issue by hippocritical** [freqtrade/frequi#2071]
**FreqUI Version**

- Version of freqUI: 1.2.5 (Available in the top right corner of the UI)
- version of freqtrade: 
works in 2024.7.1
does not work in 2024.8.1 and the current dev in docker, and in the current dev in bare metal too

**Describe the bug**
Frequi webserver points likely to the wrong column since ccxt moved from name to classname to point to lowercase exchange names

**To Reproduce**
1. Go to pairlist generator
2. select volumepairlist and for example binance (which will show up as capital B Binance)
3. See error

**Expected behavior**
change back to lowercase versions (binance instead of Binance)

**Screenshots**
![grafik](https://github.com/user-attachments/assets/35c1ea78-ef42-403d-8fb7-cd58972c6756)
(
![grafik](https://github.com/user-attachments/assets/cb056cc4-76b8-4a37-8c2c-d0ebd2c8883a)

ps:
thanks to Nin on the freqtrade discord for reporting this bug!

**Comment by xmatthias** [comment]
Nice spot - i wouldn't blame ccxt for it though - it's the changes i made for list-exchanges (to have it look nice) which broke this, as the meaning of `exchange.name` changed.
