### ISSUE TITLE
Displaying graphs in frequi

### ISSUE THREAD

**Issue by xmatthias** [freqtrade/frequi#21]
# Introduction 
For Freqtrade, we're currently using plotly.py, which offers interactive graphs.

However, experience has shown, that plotly has performance problems with larger plots, so i'm not entirely happy with it.

## Backend or frontend?

Now for FreqUI, we have a difficult decision to take:
* Do we want to Generate plots in the backend (use plotly.py and generate graphs which are then shown in the frontent)
* Do we want to use a JS graph library (plotly.js - or something completely entirely) to generate the plots in the frontent.

To me, the 2nd option seems better, as it will allow us better interactivity (we might be able to feed it with data as selected, so not the whole graph must be drawn every time).

## What types of graphs we need

To start, we will need simple graphs (for aggregated views) as well as candlestick graphs, so the selected component should support:

* Line
* Bar-chart
* Pie-chart
* Candlestick

Existing Backend plotting (plotly.py) would support all of the above graphs.

## Possible graphing libraries:

The following lists a few vue-components which are supposed to allow easy interaction from a vue.js application: [link](https://awesome-vue.js.org/components-and-libraries/ui-components.html#charts).

Libraries which seem interresting at first glance (links go to the vue-version of the libraries).

* [vue-echarts](https://github.com/ecomfe/vue-echarts) - ECharts component for Apache eCharts - [candlestick-examples](https://echarts.apache.org/examples/en/index.html#chart-type-candlestick)
* [vue-chartjs](https://github.com/apertureless/vue-chartjs) 
* [vue-plotly](https://github.com/David-Desmaisons/vue-plotly) (counterpart to backend plotting)
* [v-chart-plugin](https://github.com/ignoreintuition/v-chart-plugin) - D3 plots in a vue application

Now i've got no experience with either of the above libraries - but i hope someone else has and can provide some help in selecting a well performing graphing component.
Experience must not be with the vue-version of the libraries though - as the main selection criteria should be the underlying graphing library, not the vue wrapper..

**Comment by xmatthias** [comment]
After doing a bit of investigation:

### chartjs

it seems like `chartjs` does not natively support financial (speak candlestick) charts. that kindof eliminates it as that's our main plotting target (i think).

### D3

D3 itself is not really a visualization library (at least they claim themselfs: "D3.js is a JavaScript library for manipulating documents based on data")

**Comment by felpasl** [comment]
With end-user experience, up vote to vue-echarts [big data](https://echarts.apache.org/examples/en/editor.html?c=candlestick-large) very fast ui with good capabilities.

about graph some suggestion, a % graph with comparing buy/hold stake currency compared with simulated wallet balance on backtest / wallet on a trading session like 
![graph](https://cms.trustnet.com/Media/Default/Images/Graphs/20170317_John_Wood_leaves_JO_Hambro_buy_hold_fold_fund_UK_equities_1.png)

**Comment by xmatthias** [comment]
I do agree with all of your points - and i even started a sample with echarts.

I think the benefits of using frontend will outweight generating the graph in the backend - AND it will reduce the strain on the backend - which is doing "important" operations by  trading ...

with "what types" i was more about the types of graphs (bar, candlesticks, linechart) ... 
Which metrics we're showing is then a different topic, and will for sure be increasing with time ...

**Comment by hroff-1902** [comment]
Tradingview charting lib:
https://www.tradingview.com/HTML5-stock-forex-bitcoin-charting-library/

The lightweight version is Apache licensed

**Comment by xmatthias** [comment]
I know that one - but it's limited to lines / candlestick charts - which limits us quite heavily. 
The biggest problem is, you can't even do a Barchart (for example to show the asset distribution).

Also, the free lightweight version has quite heavy limitations...

now i'm not excluding it "just because" - but if possible i'd stick to one library for charting instead of mixing 2 in one project ... (now if it's not possible, this will always be the fallback for candlestick charts...)

**Comment by felpasl** [comment]
Feature toggle on this in the future. Starts in the easiest way.

**Comment by leeoniya** [comment]
have a look at uPlot ;)

https://github.com/leeoniya/uPlot#performance

**Comment by yohplala** [comment]
Hello @leeoniya , Wouldn't starting directly with Timechart that you mention in your benchmark be better?
https://github.com/huww98/TimeChart

**Comment by xmatthias** [comment]
do either of these 2 libraries have a vue wrapper component?

Now writing one would not be that complicated, but it's always better to reuse what exists already.

---

for TimeChart - it does not seem to support candlestick charts - and i'm not keen on writing that part myself  (that's not what we should focus on!).
So while performance seems nice (without testing - but knowing that it uses webGL) - i think it's not worth it...

---

As said, i'm not 100% convinced on either route yet.

I started for now with eCharts (doing some experiments ...) - and plotting something simple seems easy and straightforward.

Can't say anything about performance yet - but while keeping performance in mind, for a candlestick diagram, we can't realistically display more than a few 100 candles on a screen - simply because it does not fit graphically - so i'm not sure if using a library that allows millions of points is not shooting birds with canons ... 

However, i'll try to have a try with most of the above mentioned.

**Comment by leeoniya** [comment]
> Hello @leeoniya , Wouldn't starting directly with Timechart that you mention in your benchmark be better?

the author did a perf comparison against uPlot a while back. when i first noticed TimeChart it was pretty rudimentary and experimental, and by the looks of it, it still is. I dont really consider it to have enough features or API surface to be much more than a raw signal & waveform display.

https://huww98.github.io/TimeChart/docs/performance

this test does not have autoranging turned on in TimePlot, but has it enabled in uPlot, which makes the perf comparison not quite apples-to-apples.

i also did a per comparison vs https://github.com/tradingview/lightweight-charts but removed it from the table because could not get it to render the bench in its entirety:

https://github.com/leeoniya/uPlot/issues/185

if uPlot is too bare-bones for you, you can still use the perf & size table to do much better than Echarts :D

**Comment by DomenikPasquale** [comment]
+1 for frontend.

+1 for trading view 'lightweight-charts', because:

I use trading view as my primary analysis tool.  When I need to make decisions, I tend to perform better when the charting tools looks|operates the same.  
and I get they're not 100% the same; but it's close enough for basic analysis. 


-2 because:
From what I can tell, 'lightweight-charts' lacks 'event marks' -- and seeing markers for events (such as trade enter|exits) is important to me.  

Their 'charting-library' product does support event-marks, and (as I understand) would require users to obtain a license via a signed contract... which I believe is outside the focus of this project.


For initial development, I support leveraging a single library if that library can do-it-all.  I would make an exception within an analysis view if trading view 'lightweight-charts' supported event marks.  hmm...

+1 for the analysis view being modular.

**Comment by xmatthias** [comment]
it won't be lightweight charts (the tradingview library) for the moment, as that would mean we'd need 2 libraries.
Also, the only version we'd be allowed to use is the lowest level (open source) - and that is VERY limited - no drawing tools, not even cursor sync (to allow zooming in on one chart, and also zoom in on the below RSI chart).


I'm playing with e-charts - and performance (and usability) is pretty good so far (especially considering that we'll not have millions of candles at once) - and it also looks quite good i think ([echarts example](https://echarts.apache.org/examples/en/editor.html?c=candlestick-sh-2015)).

Neither will have the "drawing tools" you know from tradingview (the page) - so an analysis view would have to be built manually - but to be honest, replicating tradingview is not the point of the UI, it's to give you a quick glimse at what's happening with the bot in real time - and (at a later point) also where the signals are in backtesting.

If you wanna do analysis - go to tradingview (or the exchange, which also uses tradingview in 90% of the cases).

**Comment by felpasl** [comment]
> it won't be lightweight charts (the tradingview library) for the moment, as that would mean we'd need 2 libraries.
> Also, the only version we'd be allowed to use is the lowest level (open source) - and that is VERY limited - no drawing tools, not even cursor sync (to allow zooming in on one chart, and also zoom in on the below RSI chart).
> 
> I'm playing with e-charts - and performance (and usability) is pretty good so far (especially considering that we'll not have millions of candles at once) - and it also looks quite good i think ([echarts performance example](https://echarts.apache.org/examples/en/editor.html?c=candlestick-sh-2015)).
> 
> from the UI so far:
> 
> ![2020-06-17-203854_1915x726_scrot](https://user-images.githubusercontent.com/5024695/85191552-9b2aea00-b2bf
> Neither will have the "drawing tools" you know from tradingview (the page) - so an analysis view would have to be built manually - but to be honest, replicating tradingview is not the point of the UI, it's to give you a quick glimse at what's happening with the bot in real time - and (at a later point) also where the signals are in backtesting.
> 
> If you wanna do analysis - go to tradingview (or the exchange, which also uses tradingview in 90% of the cases).

I igree, for me ideas for viewpoints. 
1. view backtesting results profit and per pair like actual ploty,
2. during trade command view buy, sell signals, trades and strategy indicators, live table trades with profit.
3. %wallet vs %price compare

**Comment by xmatthias** [comment]
using eCharts i'm pretty far i think (but currently, the endpoint in freqtrade is missing for that).


![2020-07-01-205300_1770x927_scrot](https://user-images.githubusercontent.com/5024695/86514785-9a906880-be14-11ea-89c1-c8da063c921f.png)

I've also got a small "daily" graph - but that was more to see how eCharts would work than what it's actually great.

Stay tuned - this will come - and i think you'll like it :+1:
