### ISSUE TITLE
Set timezone for webUI

### ISSUE THREAD

**Issue by jbishop129** [freqtrade/frequi#211]
Wondering if it’s currently possible to set the timezone so trades and stats in the UI are localized? I’m running as a container and tried the usual
```
volumes:
  - /etc/timezone:/etc/timezone:ro
```
  
.. but to no avail.

**Comment by xmatthias** [comment]
currently, the only value that can be localized will be the chart. everything else is in UTC.

If any, it'll need to be changed wherever it's shown to use the browser's timezone. that way, it's irrelevant what timezone the server is in.

**Comment by jbishop129** [comment]
Makes sense, thanks for the explanation
