### ISSUE TITLE
Line Plot (alternative to the  default Candlesticks option) in the Main Plot

### ISSUE THREAD

**Issue by danpeterson24** [freqtrade/frequi#2142]
Operating system: Windows 10
Python Version: Python 3.11.2
CCXT version: 4.4.24
Freqtrade Version: freqtrade 2024.10

It would be convenient to have the **line** plot as one of the default options for displaying data in the main plot. Currently, only candlesticks are available as the default plot style. I'm talking about permanently staying on the line plot, without having to switch the candles off on every refresh. Is that possible?

**Comment by xmatthias** [comment]
it's not currently possible - and i'm not sure it's a feature worth having if i'm honest.

What'd be the usecase to not have the candles, but instead just have a line (overlapping with the probably 20 other indicator lines you've got)?

**Comment by xmatthias** [comment]
Closing this as i
a) don't see the usecase
b) we got no further feedback on this issue.
