### ISSUE TITLE
Visualize backtesting report in frequi

### ISSUE THREAD

**Issue by sethemis** [freqtrade/frequi#247]

**Comment by xmatthias** [comment]
At the moment, you cannot. 
Use `freqtrade backtesting ...` to run it in the terminal (and look at the results in the terminal)

While I'm working on it, but it's still quite a long way until that'll be ready and stable.

**Comment by xmatthias** [comment]
This has actualy been implemented a while ago (available with [2021.7](https://github.com/freqtrade/freqtrade/releases/tag/2021.7)).

You can start freqtrade with `freqtrade webserver <...>` - launch the UI, and start / control your backtests from there.

It might not be perfect yet, but it'll give the same results / information than regular backtesting does.
