### ISSUE TITLE
Allow at least 4 decimal digits when forcing a purchase

### ISSUE THREAD

**Issue by jaesbit** [freqtrade/frequi#255]
https://github.com/freqtrade/frequi/blob/35bc07f911ee37e7c931429eef587e72f5cb4c7f/src/components/ftbot/ForceBuyForm.vue#L29

From what I have seen, to allow more decimals you have to increase the amount of decimals in the step attribute.

Would it be possible to change to a step with more decimals like 0.00001

**Comment by xmatthias** [comment]
in theory - yes

the downside to this is that it'll heavily depend on your stake pair.
if you're on USD/USDT/EUR/ ... - then 2 decimals are perfectly fine, and having the wheel spin with 6 (or 8) decimals will be highly anoying

if you're on BTC pairs though, you'll probably need 8 decimals, not just 6 ... but again, it'll depend on the pair.
