### ISSUE TITLE
Overlapping Left Y-Axis and the Label in the Daily Profit and Cumulative Profit

### ISSUE THREAD

**Issue by varunrai** [freqtrade/frequi#258]
Overlapping Left Y-Axis and the Label in the Daily Profit and Cumulative Profit

1. Open the Dashboard
2. View the Cumulative Profit and Daily Profit charts

**Expected behavior**
There should be a spacing between the axis and the label

**Screenshots**
![chrome_2lNDrWp403](https://user-images.githubusercontent.com/1327311/107490287-a622e980-6bc4-11eb-97d7-a6aa15d34ffe.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 88

**Comment by xmatthias** [comment]
won't this be fixed with #257 too ? at least it seems that way ... ?

**Comment by varunrai** [comment]
yes. it does i was going to update the PR description but it was already approved.

**Comment by varunrai** [comment]
Resolved by #257. Hence closing the issue.

**Comment by xmatthias** [comment]
> yes. it does i was going to update the PR description but it was already approved.

yeah - sometimes i'm fast (sometimes slow, too) 😆
