### ISSUE TITLE
Trade Log chart change type to bar with color coding

### ISSUE THREAD

**Issue by varunrai** [freqtrade/frequi#259]
The current trade log chart looks very messy especially when viewing a large amount of trades. 

Would like to propose the chart changed to bar type with color coding to indicate +/- profits.
![image](https://user-images.githubusercontent.com/1327311/107494407-b6899300-6bc9-11eb-93fe-313573cb946a.png)

Additionally, limit the data displayed to be the last 30 trades but the user would have the capability to view all the trades.

**Comment by xmatthias** [comment]
i guess the limitation can be done by setting the default zoomlevel - so all data is available - but the last 30 (or whatever) are focused in on.

Now i am not sure if a barchart will really look better - considering your screenshot shows a volume chart - but for this data, we'll have green bars > 0 - and red bars < 0 ... so it might look odd as green and red will be starting from 0, and fluctuate to the top and bottom.
It's difficult without properly seeing this though - but i'm absolutely open to enhancements - how to display which data is always subjective, and if it can be improved, even better!

**Comment by varunrai** [comment]
I will come up with a sample and then we can decide if it looks better or worse.
