### ISSUE TITLE
Error starting userland proxy: listen tcp4 127.0.0.1:8080: bind: address already in use

### ISSUE THREAD

**Issue by IHateNameStealers** [freqtrade/frequi#266]
Hi all,
I'm sure it's me, and I know that FreqUI is still in alpha testing.
However. I wanted to play with it a little bit, and after installing it on my test Ubuntu server I was hoping to do so.

Unfortunately after trying for some time now I'm not able to start both FreqUI and Freqtrade.
IE: Freqtrade is working fine when started, and I can get the API to respond with the http://127.0.0.1:8080/api/v1/ping {"status": "pong"}
When trying to start FreqUI, I get an error that the port is already in use.
When I start FreqUI (before starting Freqtrade) I am able to access the FreqUI webinterface, but not Freqtrade as it is not running!

In the rest-api readme it tells me to uncomment the "ports - "127.0.0.1:8080:8080" in the docker-compose file.
I did not have this in the docker-compose.yml, so I've added this myself.

Anyone here who might see what I've done wrong?

/home/ihatenamestealers/ft_userdata/docker-compose.yml
```
---
version: '3'
services:
  freqtrade:
    image: freqtradeorg/freqtrade:stable
    # image: freqtradeorg/freqtrade:develop
    # Use plotting image
    # image: freqtradeorg/freqtrade:develop_plot
    # Build step - only needed when additional dependencies are needed
    # build:
    #   context: .
    #   dockerfile: "./docker/Dockerfile.technical"
    restart: unless-stopped
    container_name: freqtrade
	#needed port/ip for freqUI
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - "./user_data:/freqtrade/user_data"
    # Default command used when running `docker compose up`
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/tradesv3.sqlite
      --config /freqtrade/user_data/config.json
      --strategy SampleStrategy

```	  
/home/ihatenamestealers/ft_userdata/user_data/config.json
```
..
..
 "api_server": {
        "enabled": true,
        "listen_ip_address": "0.0.0.0",
        "listen_port": 8080,
        "verbosity": "info",
        "enable_openapi": true,
        "jwt_secret_key": "somethingrandom",
        "CORS_origins": ["http://127.0.0.1"],
        "username": "ihatenamestealers",
        "password": "yesIdo"
    },
..
..

```
/home/ihatenamestealers/frequi/docker-compose.yml
```
---
version: '3.8'
services:
  frequi:
    build:
      context: .
      dockerfile: "./Dockerfile"
    image: frequi
    # image: freqtradeorg/frequi:master
    restart: unless-stopped
    ports:
      - "8080:80"
```

ERROR:
```
ERROR: for freqtrade  Cannot start service freqtrade: driver failed programming external connectivity on endpoint freqtrade (130738809b3b3fe6d30d4e68f9a48w267ef7232ddw7b54312ed1a9a8c2268333): Error starting userland proxy: listen tcp4 127.0.0.1:8080: bind: address already in use
ERROR: Encountered errors while bringing up the project.

```

**Comment by xmatthias** [comment]
you'll need to use a different port for Frequi. 
You can't start 2 different processes (or docker-containers) that both use port 8080.

If it's just about using freqUI, i would recommend using the develop branch / image of freqtrade, which has freqUI included.

**Comment by IHateNameStealers** [comment]
Thank you for the update Matthias,
Yes I did try this too., And I did manage to get them both up and running. 
(I think that is was something like this)
Freqtrade / docker-compose.yml on "127.0.0.1:8081:8080"
Freqtrade / config.json on "0.0.0.0" and 8080
and FreqUI docker-compose.yml on 8080:80

However. When I tried to login, FreqUI kept telling me something about making sure that I could access the "ping" (witch I did), and that CORS needed to be setup.

Anyway. As this is a test setup I'm going to give the develop branch a run.

**Comment by matty87a** [comment]
@IHateNameStealers - how did you get on with the develop branch? I have been running into the CORS issue too despite it being configured and being to access the swaggerUI without issue

**Comment by IHateNameStealers** [comment]
I did test the develop branch, and got it all working. After that I decided to give the docker version a try again, and I did manage to get it to work too.

My setup looks like so: (10.0.0.157 is the IP of the system where my Freqtrade and Frequi are running on)
home/ft_userdata/user_data/config.json
```
    "api_server": {
        "enabled": true,
        "listen_ip_address": "0.0.0.0",
        "listen_port": 8080,
        "verbosity": "info",
        "jwt_secret_key": "somethingrandom",
        "CORS_origins": ["http://10.0.0.157"],
        "username": "54321",
        "password": "12345"
```

home/ft_userdata/docker-compose.yml
```
---
version: '3'
services:
  freqtrade:
    image: freqtradeorg/freqtrade:stable
    restart: unless-stopped
    container_name: freqtrade
    volumes:
      - "./user_data:/freqtrade/user_data"
    ports:
      -  "10.0.0.157:8080:8080"
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/tradesv3.sqlite
      --config /freqtrade/user_data/config.json
      --strategy Simple
```
/home//frequi/docker-compose.yml
```
---
version: '3.8'
services:
  frequi:
    build:
      context: .
      dockerfile: "./Dockerfile"
    image: frequi
    # image: freqtradeorg/frequi:master
    restart: unless-stopped
    ports:
      - "80:80"
```

After starting both "containers" I'm able to access the FreqUI and Freqtrader.
Use as URL (in my case) http://10.0.0.157, and when asked for API Url, use (again in my case) http://10.0.0.157:8080

**Comment by xmatthias** [comment]
if you're using the develop version, you do not need the frequi container anymore.

Simply navigate to the url of the freqtrade container's root url (probably `10.x:8080`  and you should be up and running.
You'll also not need CORS with that setup.

**Comment by IHateNameStealers** [comment]
That is correct, and as mentioned above I did manage to get that to work. However. I wanted to try this with the none dev. version.

**Comment by xmatthias** [comment]
Then it's fine :+1:
