### ISSUE TITLE
dry_run reported on live instance, in :develop channel with built-in FreqUI

### ISSUE THREAD

**Issue by jbishop129** [freqtrade/frequi#268]
I notice "live" running instances on the latest :develop channel docker container report as dry_run mode. Does not seem to have any functional problems beyond being just a UI bug.

**Comment by xmatthias** [comment]
For now, i can't recreate this, for me it correctly shows "Live", whereas test instances show as "Dry-Run".


Are you able to open developer tools and use the network tab, and show me the content of the response of the call for `show_config`.
You can trigger this call by clicking the big refresh button at the top.

**Comment by jbishop129** [comment]
@xmatthias this is my mistake. I posted this in the wrong project. I intended to post this in the /freqtrade project, and referring to the newly-available built-in freqUI built in to those builds. I'll close this out as being incorrectly reported. Thanks for all you do, this is a great project!

**Comment by jbishop129** [comment]
(issue reported in wrong project)

**Comment by xmatthias** [comment]
i moved it to frequi, as the builtin frequi is just the latest release of this project.

I don't see it happening however, which makes me suspect it might be related to your settings (you think it's live, but it isn't).

**Comment by jbishop129** [comment]
Hi @xmatthias I was able to reproduce this in the Developer tools, network tab as requested. Here's a screenshot, where you can see FreqUI shows "Dry-Run", but the `/show_config` indicates it is indeed live (and indeed watching my Binance.us account, it's certainly live.  For what it's worth, I have tried different browsers and different computers to rule out cache, and this is occurring on both of my "live" instances, one on Kraken, the other (shown here) Binance.us. As far as I can tell, it's a non-impactful UI bug; I have not seen any functional problems because of it.

docker image: `freqtradeorg/freqtrade:develop`


<img width="613" alt="image" src="https://user-images.githubusercontent.com/28128937/108603117-4f0ada80-7363-11eb-85c4-4d09ad453d60.png">

**Comment by xmatthias** [comment]
hm, interresting, my bot returns a boolean for this.

will need to check which version i'm running ...

**Comment by jbishop129** [comment]
Thank you @xmatthias, I `docker pull freqtradeorg/freqtrade:develop` and redeployed, it shows `live` now, and bonus! My other issue (which I'll close), it also shows the Close Reason column I was hoping to see.

Cheers!
