### ISSUE TITLE
Hourly Profit chart, highlight the current hour

### ISSUE THREAD

**Issue by jbishop129** [freqtrade/frequi#270]
**Is your feature request related to a problem? Please describe.**
No. Just an improvement for added usability

**Describe the solution you'd like**
Because FreqTrade operates on UTC time, and the Hourly Profit is a rolling 24 hour snapshot of how your bot is performing, it takes some back-and-forth between the Dashboard and Trade tabs, first to check "what UTC hour are we operating in right now?" then back to Dashboard, to see how this and recent hours are performing. It would be great if the bar graph (trade count) piece of the Hourly Profit would show the current hour in a different color (light blue) while all the remaining bars for the trade count in that graph remain light gray. This way, at a glance, you'd quickly know what hour it is operating in at this time.

**Describe alternatives you've considered**
None. My idea is the best ;) kidding.

**Additional context**
Just that it would make the at-a-glance dashboard that much better

**Comment by xmatthias** [comment]
i'm not sure about the benefit of this (and i do think you misunderstand the "24h" dashboard view.

It's not rolling - but it's an aggregation of "per hour" trades - so you could say that your strategy is in general not good when it sold a trade at 2am.
It's not rolling - so the current hour highlight will lose it's benefit once the bot runs for 2-3 days (as it's an average over multiple days - not a rolling view).


The "hourly" chart is basically for analysis only - once your bot runs for 2-3 days you'll no longer be able to see changes of "today" within that chart - as it's an aggregation per hour (it's NOT containing .

I don't think you'll find the color highlighting beneficial after a few days of running, as the current hour's trading is not really relevant once your "days running" is above a (very small) certain point.

**Comment by jbishop129** [comment]
Thanks for the detailed explanation, and this certainly clears up some head-scratching I’ve had on longer running bots. Indeed it “seems” to be a rolling 24hr chart, when one looks at a newly launched instance (less than 24hr of runtime, or not much longer than), but as you describe it and I go back and look at some bots that have been running for much longer, I see what you mean. Thanks again, and I’ll close ‘er out!
