### ISSUE TITLE
Gui and iPad Pro

### ISSUE THREAD

**Issue by nodwan** [freqtrade/frequi#275]
hi, i‘m using my ipad pro for monitoring, and all works ashly fine, but what i’have to say, to touch the silder, is terrible ... on a ipad ... may in the future it will be better useable , i‘hope ...

**Comment by xmatthias** [comment]
Which slider are you talking about?

Letme be honest, usability on smaller screens is currently not a priority - it's optimized for a fullhd screen, not for tablets, phones or touch screens in general.
