### ISSUE TITLE
multiple bots - frequi is accessible only on the first one

### ISSUE THREAD

**Issue by aristosv** [freqtrade/frequi#284]
**Describe the bug**
freqUI cannot present web gui if "listen_port" is other than 8080.

**To Reproduce**
Set up multiple bots on the same server and define different ports on the "listen_port" value for "api_server".

**Desktop (please complete the following information):**
 - OS: macOS Big Sur v11.1
 - Browser Safari v14.0.2

**Additional context**

I've set up 3 bots on the same server, each one with it's own "listen_port", but only the first one works. The others are inaccessible.

```
    "api_server": {
        "enabled": true,
        "listen_ip_address": "$ip",
        "listen_port": 8080,
        "verbosity": "error",
        "enable_openapi": false,
        "jwt_secret_key": "$secretkey",
        "CORS_origins": [],
        "username": "$user",
        "password": "$pass"

    "api_server": {
        "enabled": true,
        "listen_ip_address": "$ip",
        "listen_port": 8081,
        "verbosity": "error",
        "enable_openapi": false,
        "jwt_secret_key": "$secretkey",
        "CORS_origins": [],
        "username": "$user",
        "password": "$pass"

    "api_server": {
        "enabled": true,
        "listen_ip_address": "$ip",
        "listen_port": 8082,
        "verbosity": "error",
        "enable_openapi": false,
        "jwt_secret_key": "$secretkey",
        "CORS_origins": [],
        "username": "$user",
        "password": "$pass"
```

**Comment by xmatthias** [comment]
how are you running frequi? via the freqtrade integration (served from freqtrade)?
installed directly and running with `yarn serve`?

**Comment by aristosv** [comment]
via the freqtrade integration (served from freqtrade)

This is how I install it for each bot.

```
source .env/bin/activate
freqtrade install-ui
deactivate
```

**Comment by xmatthias** [comment]
How are you accessing it? what exactly is the error?

i've just tried, and accessing both `localhost:8081` and `localhost:8082` works flawlessly for me.
Obviously, you'll need to be careful using the correct IP to login for the correct bot.

**Comment by aristosv** [comment]
I am accessing them all through Safari on my computer. This is the error.
![Greenshot 2021-03-03 20 25 26](https://user-images.githubusercontent.com/528302/109853504-a01da700-7c5e-11eb-88bb-8c16dd1bccb3.png)

The firewall allows connections from my IP only, to those ports only.
![Greenshot 2021-03-03 20 23 25](https://user-images.githubusercontent.com/528302/109853588-b75c9480-7c5e-11eb-8305-defcf452f515.png)

And these are the URLs I use to connect
![Greenshot 2021-03-03 20 22 04](https://user-images.githubusercontent.com/528302/109853631-c7747400-7c5e-11eb-9700-9adda8dd767c.png)

I tried from my phone also, but it's the same result. It's the same IP for all the bots since they are all on the same server. The strange thing is that the first bot on port 8080 works fine.

**Comment by aristosv** [comment]
I just changed the port to one of the bots to 65534 and now it's accessible. It probably has to do something with the host limitations. Sorry for the trouble, closing this now.

**Comment by xmatthias** [comment]
strange ... but yeah, it's possible that 8081 is somehow a reserved port (used by another application for something else) - or at least reserved for that.

i guess it'll depend on the system / what you've got running there.
