### ISSUE TITLE
Info request - buy, sell, trades, trades close  

### ISSUE THREAD

**Issue by YuriyTigiev** [freqtrade/frequi#304]
Hello, 

What does mean "Buy" and "Sell" marks on the main chart?  For what we should use it? Can I hide it?
As I understand the real buy is marked as "Trades" and the sell as "Trades Close". Is it correct?

![freqtrade_buy_sell](https://user-images.githubusercontent.com/22752322/112755316-2c6a8200-8ff1-11eb-9e4b-56f6f5ae5d32.PNG)

**Comment by xmatthias** [comment]
It's buy / sell signals - signals your strategy is giving.

You can hide them by ticking at their symbol at the top - but they will always be part of the graph and cannot be disabled.
