### ISSUE TITLE
Negative values in Daily Profit chart not visible

### ISSUE THREAD

**Issue by klara31** [freqtrade/frequi#310]
**Describe the bug**
The Daily Profit chart shows a line chart of the daily profit. However, only above 0 a line is visible, the negative dots are not connected
<img width="255" alt="Schermafbeelding 2021-04-04 om 12 09 31" src="https://user-images.githubusercontent.com/1309136/113505387-d17be200-953e-11eb-8e62-323e376c8686.png">

**To Reproduce**
1. Go to Dashboard
2. Scroll down to Daily Profit chart

**Expected behavior**
There should be a line connecting all the dots, both above and below the x-axis.

**Screenshots**
See above

**Desktop (please complete the following information):**
 - OS: MacOS BigSur
 - Browser: Safari AND Chrome

**Comment by xmatthias** [comment]
that chart looks strangely small - so probably you've resized it to be too small.

Also, you need to "scroll down" - while the daily profit chart is in the top right corner by default, which supports this assumption.

Please use the "reset layout" button while on the dashboard - then it should show up again.

Confirmation that it's working fine:
![2021-04-04-172822_482x334_scrot](https://user-images.githubusercontent.com/5024695/113513730-60065880-956b-11eb-93a5-c70a59edac0b.png)

**Comment by klara31** [comment]
Reset layout does not solve the problem, resizing the chart neither. The hourly profit is showing correctly!

**Comment by xmatthias** [comment]
anything in the devtools console output?

Also, how are you running this - as "release" or via `yarn serve` from a cloned repository?

**Comment by klara31** [comment]
I have cloned (and pulled the latest version from) the git repository and use ```docker-compose --build``` to create the docker container running frequi.

Devtools console is empty, no error or warning messages.

**Comment by epigramx** [comment]
Been seeing the same for a while, on two different machines. I only used install-ui though (which gets 0.0.5 now(I don't know if it's easy to get the latest to replace whatever install-ui gets)).

**Comment by epigramx** [comment]
Odd: on chrome it's dots without lines. On firefox it's progressively lighter green the lower it is.

Check more browsers I guess to see if you get anything different there.

**Comment by epigramx** [comment]
Not sure what .vue files even are entirely tbh but I copy pasted HourlyChart.vue'a visualMap (which was working correctly) to DailyChart.vue's (of this issue's) and after zero'ing the max and mins it seems to work correctly.

![image](https://user-images.githubusercontent.com/2960257/114077192-31141d80-98b0-11eb-83f0-46496dd77265.png)

Not sure why it's even trying to not be 0 and 0 but some values close to zero either since it seems intuitively correct to center it around 0 (but as I said I don't really understand that framework).

**Comment by klara31** [comment]
I can confirm that the above solves the issue.

**Comment by xmatthias** [comment]
Closed by #315
