### ISSUE TITLE
Cannot change plot configuration

### ISSUE THREAD

**Issue by klara31** [freqtrade/frequi#320]
**Describe the bug**
When entering the plot configuration, a new window is opened in which the plot configuration can be changed. When trying to add an indicator, nothing happens. Chrome developer tools shows in the console the following error:
```
vue.runtime.esm.js:1888 TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at a.get (PlotConfigurator.vue:224)
    at nr.get (vue.runtime.esm.js:4479)
    at nr.evaluate (vue.runtime.esm.js:4584)
    at a.usedColumns (vue.runtime.esm.js:4836)
    at a.R (PlotConfigurator.vue?e1e3:1)
    at a.t._render (vue.runtime.esm.js:3548)
    at a.r (vue.runtime.esm.js:4066)
    at nr.get (vue.runtime.esm.js:4479)
    at nr.run (vue.runtime.esm.js:4554)
```

**To Reproduce**
1. Go to Trade page
2. Click on wheel (top right)
3. Add indicator to used indicators

**Expected behavior**
I was able to change the indicators, but it does not work anymore.

**Screenshots**
![image](https://user-images.githubusercontent.com/1309136/114419801-0974cc00-9bb4-11eb-86dc-f0793f1da69c.png)

**Desktop (please complete the following information):**
 - OS: Windows 10, MacOS BigSur
 - Browser: Chrome, Edge, Safari

**Additional context**
I have cleared cache, deleted cookies, tried Incognito mode. None is working. Tried on both Windows and MacOS.

**Comment by xmatthias** [comment]
please try the "show" button and post the content that will show in the textbox below that (please copy/paste the text, don't take a screenshot of the text 😆

**Comment by klara31** [comment]
When I press the Show button, nothing happens. Also nothing in the dev tools console.

**Comment by xmatthias** [comment]
what about "load from strategy"?
Also maye check the "Application" / storage tab ... the "ft_custom_plot_config" key is the one that stores this - maybe try to remove this (although private mode would do that too ...).

**Comment by klara31** [comment]
No response on any of the buttons.
However, Clear site data from the Application/Storage tab solves the issue. Weird, as it did not work in Incognito either... It makes you start to doubt yourself...

**Comment by xmatthias** [comment]
Please let me know if it reappears.
obviously it shouldn't happen - but i also have no idea what brought you into the state of "non-working" ...

**Comment by klara31** [comment]
I am still experimenting with different strategies for my bot, maybe that triggered this somehow. I will close this issue and if it happens again, I will reopen it and hopefully know why...

**Comment by Gaz83** [comment]
Just starting out with FreqTrade and I have the same issue reported above.  Clear site data from the Application/Storage tab is not solving the issue.

Currently have 3 bots running (Docker on Windows)
Using the following strategies from the Strategies repository.

Scalp
Low_BB
TDSequential

**Comment by echoyilmaz** [comment]
I'm using Firefox browser, when I got this error and tried chrome, everything started working. I cleared the firefox history and it was fixed. Since it works with vue, it is necessary to focus on the client side. Sorry for the bad english, I google translated :)
