### ISSUE TITLE
Sort closed trades by close date descending

### ISSUE THREAD

**Issue by cornytrace** [freqtrade/frequi#327]
**Is your feature request related to a problem? Please describe.**
Right now the closed trades are sorted by id ascending. This means that the newest closed trades are at the end of the list, sometimes even on another page. This while the newest closed trades are viewed most, e.g. to see what the bot has been up to.

**Describe the solution you'd like**
I would prefer the closed trades list to be sorted by close date descending. Even better would be to sort by arbitrary columns in both directions, but that's not as high of a priority for me.

**Comment by xmatthias** [comment]
I assume you're using the freqUI release.

On master, the sorting is now by trade_id descending. It's a ... discussion point if trade_id or close_date is the better sorting logic i'd think...

**Comment by cornytrace** [comment]
I see. Thank you for taking the time to answer my question. Personally I would prefer a chronological ordering, as long-running trades interspersed with shorter ones can give quite the fragmented view IMO.

**Comment by xmatthias** [comment]
closed by af28257, will create an update shortly
