### ISSUE TITLE
Report on Freqtrade server status/errors

### ISSUE THREAD

**Issue by edebie** [freqtrade/frequi#328]
**Is your feature request related to a problem? Please describe.**
No. But it would be nice if the web interface can report on server errors. For example, if I change something in the config file and that change was incorrect, the Freqtrade docker exits or keep restarting without notifying the web UI with the problem.

**Describe the solution you'd like**
The web UI can have an event log with a button on the system bar to open and read them.

**Comment by xmatthias** [comment]
as your configuration is incorrect and causes the container to stop, there is no way to notify the UI, as all processes will stop. (you will however see that the UI will show "offline" after about a minute).

As you're however changing the configuration, you're logged into the server anyway - therefore this should not be a problem to quickly check the logs after reloading the configuration.

For regular log messages, there is the log view, however for this to update, the webserver / container must be up and running.
