### ISSUE TITLE
tradeslog contains too many items

### ISSUE THREAD

**Issue by bzed** [freqtrade/frequi#333]
**Describe the bug**

The default view is basically unreable and messy with several hundred/thousand trades (numbers will depend on the screen size/resolution I guess). Also: loading so many trades probably doesn't make much sense.

**To Reproduce**
1. Do >1000 trades
2. Click on 'dashboard'
3. Look at the trades log

**Expected behavior**
I'd say limiting the trades log to the last 100 trades or the last 24h by default would make sense, or allowing to define a limit. Also reducing the amount of Text on top of the graph would make sense.

**Screenshots**

![Screenshot_20210502_024740](https://user-images.githubusercontent.com/119820/116798544-cf328680-aaf0-11eb-9dd8-4934e5e12490.png)

**Desktop (please complete the following information):**
 - OS: debian unstable
 - Browser chrome
 - Version  91.0.4469.4 dev

**Comment by xmatthias** [comment]
You'll notice the bar at the bottom of this graph. This allows you to zoom in on the graph - so you can see the details.

Limiting the log will reduce the usefulness if you want to look at all details, so that's for sure nothing we will implement.

**Comment by bzed** [comment]
@xmatthias yes, I know. But can you really figure something out on the screenshot? You can't even see the red/green bars properly anymore. And you can't read the dates. I'm not talking abour removing information, I'm talking about making it useable. And yes, I know how to uese the sliders. That doesn't help If I want to see what is shown there, its just not useable to look at more than a day or so.

**Comment by xmatthias** [comment]
Feel free to add a default zoom to the last few days if you think that's a must.

But removing data is a no-go.
