### ISSUE TITLE
Sort open trades in Multi Pane 'Pairs Combined' by open date (or ID)

### ISSUE THREAD

**Issue by klara31** [freqtrade/frequi#335]
**Describe the solution you'd like**
In the trade view, in the left column (Multi Pane), the active pairs are shown. These are sorted with the open trades at the top, and the locks at the bottom. The open trades are randomly sorted, with every page refresh, the pairs are sorted differently.  Is it possible to sort the 'Pairs Combined' similar to the 'Open Trades' pane: sort by open date (or ID)?

This is the sort order in the multi pane column:
![image](https://user-images.githubusercontent.com/1309136/116814550-d80b7280-ab59-11eb-937b-5b4f4365e484.png)

And in the open pairs column:
![image](https://user-images.githubusercontent.com/1309136/116814584-02f5c680-ab5a-11eb-98b1-a553676d6577.png)

**Comment by xmatthias** [comment]
It's interresting that i can't reproduce this (for me, the sorting remained stable).

I've now added a deterministic sort based on trade_id (ID and open_time will sort identically) - so the sorting between the 2 fields is aligned.
