### ISSUE TITLE
How do I get to the Frequi interface?

### ISSUE THREAD

**Issue by niyazikeklik** [freqtrade/frequi#336]
Hello, I'm testing the bot on my ubuntu server in local network.

I installed it with Docker and
I chose the IP: 127.0.0.1.
Username: freqtraders

but when I enter my local server's ip address (192.168.1.123:8080) into my browser on my own device on the same network, no interface meets me.

I opened the command in the docker compose file.
```
    ports:
      - "127.0.0.1:8080:8080"
```

What am I missing?

![image](https://user-images.githubusercontent.com/27292457/116895235-a4087e00-ac3b-11eb-8805-4ebb20db296d.png)

**Comment by xmatthias** [comment]
When running in docker - you'll need to:
* use 0.0.0.0 as `listen_ip_address` (so it's listening to connections through docker)
* configure docker so you can connect to it.

using the config you're using assumes you're on the SAME device - or you're using a ssh tunnel to connect to it.
```
    ports:
      - "127.0.0.1:8080:8080"
```

you CAN change this to  the below - however be aware that then everyone with access to your network will have access to the bot.

```
    ports:
      - "8080:8080"
```

**Comment by niyazikeklik** [comment]
You are great man, it worked. thank you so much

**Comment by niyazikeklik** [comment]
> Docker'da koşarken - şunları yapmanız gerekir:
> 
> * 0.0.0.0 kullanın (böylece docker üzerinden bağlantıları dinliyor)`listen_ip_address`
> * docker'ı ona bağlanabilmeniz için yapılandırın.
> 
> kullandığınız yapılandırmayı kullanmak, AYNı cihazda olduğunuzu veya bağlanmak için bir ssh tüneli kullandığınızı varsayar.
> 
> ```
>     ports:
>       - "127.0.0.1:8080:8080"
> ```
> 
> bunu aşağıdakine değiştirebilirsiniz - ancak ağınıza erişimi olan herkesin bota erişebileceğini unutmayın.
> 
> ```
>     ports:
>       - "8080:8080"
> ```
You are great man, it worked. thank you so much
