### ISSUE TITLE
Access to my API on my vps

### ISSUE THREAD

**Issue by lulu-angry** [freqtrade/frequi#337]
Hello frequi team,

I tried to acces to my freqtrade located on my vps (US) from another computer but when i insert my vps adress in "api url" section
an error occured, i think the problem may come from the localhost of the vps but i'm not sure because i have an external adress but nothing working, do you have a solution ? or this feature can be used like this?

thank you in advance :)

**Comment by xmatthias** [comment]
by default, all configurations bind to localhost (127.0.0.1).

Depending on how you run freqtrade/frequi - it will slightly differ where / how you need to change this (Docker-compose file, 

While you can change this to listen on all ports - we do not recommend this without further considerations.
In general, I'd recommend to either use a SSH tunnel or a VPN to access freqUI (So it should not be exposed directly to the internet).

Frequi will not use SSL by default (so you should have a reverse proxy providing this).

If you are unsure or don't know how to properly secure a webserver - then please use the SSH tunnel / VPN approach.

**Comment by lulu-angry** [comment]
i tried to change my listen port on my vps ip ip ( provided) and when i try to ping  with http://*.*.*:8080/api/v1/pong i receive {"status":"pong"} and my console a 200k

![Capture](https://user-images.githubusercontent.com/83360121/117339296-dfa38200-ae9f-11eb-911c-358ab45ee4db.PNG)

but when i use an frequi and insert my ip adress and my id i receive 400 bad request 
and on the console i can see 405 Method not allowed 

i think you i need to run frequi diferently with 

so i turned on ssh and vpn approach /ssh tunel, I teach myself and I start

**Comment by xmatthias** [comment]
if you're using a rather newish version (2021.3 i think or later) - you can just go to `http://..*:8080/` to get access without messing with CORS.

If you're not running docker, you'll first need to run `freqtrade install-ui` in your terminal to have the files downloaded / updated. 

that's also documented [here](https://www.freqtrade.io/en/stable/rest-api/)...

**Comment by lulu-angry** [comment]
Thanks a lot !! the first way worked very fine !! (i forget this option :|  )
