### ISSUE TITLE
Add a 'hide small balances' to Balances display

### ISSUE THREAD

**Issue by perkmeister** [freqtrade/frequi#339]
Binance has a neat 'hide small balances' feature that unclutters the wallet and just shows significant holdings. Could we add such a feature to freqUI? You could always show the stake token regardless of amount (e.g. USDT), but hide all the other small ones and not add them up in the final simulated balance calcuation. The threshold as to what is considered a small balance could be set in the configuration, or modified in the UI.

**Comment by xmatthias** [comment]
Nice idea - it's available in the master branch now (will be in the next release, obviously).

**Comment by perkmeister** [comment]
Great, thanks. Good work!
