### ISSUE TITLE
Add number of open trades to browser tab

### ISSUE THREAD

**Issue by perkmeister** [freqtrade/frequi#382]
It would be handy to have the number of open trades in the browser tab so we don't have to switch to the tab to see.

**Comment by xmatthias** [comment]
i'm not so certain about the usefulness of that - assuming you've got a lot of tabs open - it'll become crouded very soon - considering that we have the bot-name in the tab name already - and simply displaying a number will not be very helpful - so it'd have to be something like "3 open trades" or "3 trades" ... which won't all display anyway...

**Comment by perkmeister** [comment]
OK, just a number is what was thinking of, like the number of notifications in other apps (which I use all the time to tell me whether to bother opening the tab, and they don't say '4 notifications pending' or anythng verbose, they're just numbers). I think it would be quite handy.

**Comment by perkmeister** [comment]
I looks like this has now been implemented, thank you!
