### ISSUE TITLE
When reload config with FreqUI, in multi pane the status is not refresh

### ISSUE THREAD

**Issue by pascal00d** [freqtrade/frequi#383]
**Describe the bug**

If you change "max_open_trades" and "stake_amount" in "config.json", and reload config with FreqUI, so in multi pane the status is not refresh with the new values of "max_open_trades" and "stake_amount"

**To Reproduce**
1. change "max_open_trades" and "stake_amount" in "config.json"
2. reload config with FreqUI
3. in multi pane the status is not refresh with the new values of "max_open_trades" and "stake_amount"

**Expected behavior**
in multi pane the status is refresh with the new values of "max_open_trades" and "stake_amount"

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser chrome
 - Version 2021.5

**Comment by xmatthias** [comment]
FreqUI will by default not refresh all items / api calls.

You can simply use the "refresh" button to reload all settings if you feel something should've changed and didn't.
