### ISSUE TITLE
Add Cypress End To End testing Support

### ISSUE THREAD

**Issue by pAulseperformance** [freqtrade/frequi#4]
This is a nice to have enhancement for testing and CI.

 - Cypress is a free tool for end to end testing of user interfaces. 
 - It is a very simple testing framework that replicates user testing. So you can write a test of a user logging into freqtrade and have have a video recorded of the entire session.
- Their is no vendor lock-in and it's easier to set up than selenium.

They have a freemium business model, with a paid plan mostly for enterprises. All that includes is a dashboard for the CI. The CI isn't needed and all the features of cypress are included free or not. None of this matters though, because the dashboard is FREE for open source projects.

https://docs.cypress.io/guides/core-concepts/dashboard-service.html#Requesting-OSS-Plan-for-an-Org

I'm opening this here for future expansion. Obviously it's not needed right now, but it's an awesome tool I've recently discovered and should be noted for future integrations.

**Comment by xmatthias** [comment]
Considering we're just starting - we don't have any tests so far - and in the end, i'd like to have at least partial coverage by unit tests - but also by some form of graphical tests.

Now if it's selenium, cypress, or something else (like extraterrestial form sitting in a printer in a post office -> MiB ... ) is not really important at this point - but having something definitely is.

**Comment by GrilledChickenThighs** [comment]
Right. Not important at this point, but when the time comes I think this might be a good solution. Figured I'd share it now before I forget. :)

**Comment by xmatthias** [comment]
At least for component tests, we're now using cypress.
work on e2e is however kindof still in progress.
