### ISSUE TITLE
how to change page title

### ISSUE THREAD

**Issue by lorvent** [freqtrade/frequi#411]
Question may sound silly but i am running 6 test bots with different strategies so it has become an inconvenience to findout which each bot doing.

so i just would like to know, if there is any way to change title? ( i can hard code aswell if someone can point me correct file name)

thanks

**Comment by xmatthias** [comment]
You can set the bot_name setting in your freqtradebot configuration - so the resulting title will be `freqUI - <bot_name>`.

**Comment by lorvent** [comment]
thanks for the answer.

is there any i can remove `freqUI - ` or swap it like `<bot_name> - freqUI`

because my main motive is to jump into exact tab when 10s of tabs opened.

thanks

**Comment by xmatthias** [comment]
No, freqUI is there intentionally first, and for now we have no incentive to remove that from the start of the title.
