### ISSUE TITLE
Let the default zoom in plot be user configurable

### ISSUE THREAD

**Issue by klara31** [freqtrade/frequi#426]
**Is your feature request related to a problem? Please describe.**
The default zoom level in the plot window is fixed and now related to the dataset length. When using a timeframe of 4 hours the current default zoom takes you 2 months back, whereas for a timeframe of 5 minutes the current default zoom may be sufficient. 
It would therefore be nice if the default zoom level could be user configurable. 

https://github.com/freqtrade/frequi/blob/1b9fc4704b827946867e4f399cc21809b800d35d/src/components/charts/CandleChart.vue#L289

**Describe the solution you'd like**
Let the user set a default zoom as the number of candles to be shown. This can be configured in the plot config or settings page.

**Describe alternatives you've considered**
Default zoom is now fixed. Unfortunately I lack the programming skills in vue to make this myself.

**Comment by xmatthias** [comment]
I'd not consider it fixed, but it's designed to show the chart in a "sane" size on desktop screen size.

Obviously, it'll take you back 2 months on a longer timeframe, and 2 days on a 5m timeframe - but that's also how this works on exchanges.
I've not seen a "configure default zoom" level on binance either - and honestly, i'm not sure this makes sense / is worth the effort.

**Comment by klara31** [comment]
sounds fair
