### ISSUE TITLE
TradingView charts

### ISSUE THREAD

**Issue by dominiclapointe** [freqtrade/frequi#427]
Hi all,

**Describe the solution you'd like**
Integration of tradingView chart instead of the current charting plugin. As most of the trader are used to TV, it make the learning curve steeper to navigate in the chart. Multiple plugin offer vue/vue3 TV integration such as https://www.npmjs.com/package/trading-vue-js

Thank you

**Comment by xmatthias** [comment]
This has been looked at before (#21).

The free, open source version of tradingview charts will not allow adding additional indicators, nor will it allow subplots (like volume, MACD, RSI) - and as such will not be useful.

Using one of the "higher" level tiers is not possible from a license perspective as we distribute the application - and as such, it's impossible for us to integrate tradingview charts.

**Comment by dominiclapointe** [comment]
hum based on https://www.tradingview.com/HTML5-stock-forex-bitcoin-charting-library/?feature=technical-analysis-charts it seem that those requirement are free to use, as long as you keep the their logo.

![image](https://user-images.githubusercontent.com/47004797/125453172-f3e8747d-bc93-43d2-9f86-066c7bf1389b.png)
