### ISSUE TITLE
Frequi displays rounded rates

### ISSUE THREAD

**Issue by perkmeister** [freqtrade/frequi#439]
In the Open Trades pane, frequi displays rounded open and current rates to 3 decimal places which is not enough for some tokens, and current profit to 2 decimal places. 
Expected behaviour was to display 8 and 3 decimal places respectively as per the Trade Detail pane. 

Tested with frequi V0.1.1

**Comment by xmatthias** [comment]
FreqUI will default to 3 if your freqtrade instance does not support the option yet (which will be the case unless you're using develop).

This might be the case if you're using the stable release. Please retry with develop (or with the release that's due to come out today or tomorrow).

**Comment by perkmeister** [comment]
Thanks Matthias. I'm running the latest develop version develop-dad98d43, still gettting rounding to 3 decimal places in the Open Trades pane. It's strange as the Trade Details pane has more resolution, although this doesn't show current rate specfically it does show open rate at 8 decimal places and current profit to 3 decimal places, see screenshot
![rounding](https://user-images.githubusercontent.com/28675875/127551567-2fa1d30e-f522-477b-a9ea-c805d460fc84.PNG)

**Comment by xmatthias** [comment]
For the rates you're right - these should be "left in peace".

current profit however does not make sense in more resolution - if you made 0.001$ profit or 0.0011 will NOT change anything (it's a fraction of a penny).
While mathematically there - it's not relevant as the exchange will not exchange in this precision anyway.

Also - the rounding is dependent on the stake-currency - so for BTC stake, 8 decimals will be used (which however is pointless for USDT).

**Comment by perkmeister** [comment]
Well for current profit it's consistency more than anything as it's displayed in 3 decimal places everywhere else. The rates are rounded for other tokens that are small, like HOT and DENT (which was an 8% loss here, but open and closed rates are shown in Closed Trades here as the same). Maybe 8 significant places is the metric to use rather than decimal places?
![dent](https://user-images.githubusercontent.com/28675875/127742283-10359a67-e7b4-4776-ba5c-dffe114101b9.PNG)

**Comment by xmatthias** [comment]
If you wanna look at this further, please use the master version of freqUI (not released version yet).
