### ISSUE TITLE
Connect coinmarket cap in freqUI

### ISSUE THREAD

**Issue by HenriPiot-dev** [freqtrade/frequi#471]
Hey everyone ! 

This is not issue but an enhancement idea. 
What do you think about adding a connection with for instance coin market cap, to have additional information about a selected pair in freqUI: 
- Creation date.
- Short description of what is the crypto doing.
- Global capitalization ..

This can provide information on a crypto that is being trade by the bot !

**Comment by xmatthias** [comment]
there's 2 issues with that.
first of all, coinmarketcap doesn't provide a free api anymore - but requires a personal key.
that already had us move away from coinmarketcap in freqtrade, and i don't see that route for freqUI either.

more importantly (coinmarketcap can be replaced i guess) though - it'll provide little to no benefit.

You can research the coin yourself if you are interrested in that ... but freqUI is a UI to visualize bot status ... 
You'll not be able to act on that information other than blacklisting (the pairlist is controlled by the bot, not by freqUI).
If any, it'd be interresting to have as pairlist ... but for freqUI, there's other things that are far more important / will provide far more benefit than such an integration.

**Comment by HenriPiot-dev** [comment]
Sure I get it ! 
Thank you for the answer ! 
Henri
