### ISSUE TITLE
pairs with profit 0.0% not show is not displayed in left bar - pairs combined 

### ISSUE THREAD

**Issue by dankez** [freqtrade/frequi#499]
**Describe the bug**
when current profit is 0.00%, trade have no color,no number on left bar, 
gui 0.1.2
 freqtrade develop-4ce1375bf

screenshot - https://ibb.co/TmrGdkQ 

**To Reproduce**
1. Go to 'trade / pair combined' 

**Expected behavior**
green 0.00%

**Screenshots**
screenshot - https://ibb.co/TmrGdkQ 

**Desktop (please complete the following information):**
 - OS: mint
 - Browser chrome, chromium, firefox, midori
- ver latest. 

**Smartphone (please complete the following information):**
 - Device: android 10
 - OS: android
 - Browser brave
 - Version latest

**Comment by xmatthias** [comment]
That's a pretty tough one to reproduce  ... :laughing: 

I'm also not certain if it still reproduces in the new version (unreleased master) - as a lot changed (also in relation to how this will be rendered).
