### ISSUE TITLE
multibot

### ISSUE THREAD

**Issue by anakein** [freqtrade/frequi#559]
I have 2 raspberries with a bot each. all work fine.

from my computer, I can access both bots for frequi so that http://192.168.1.2:8080
http://192.168.1.176:8081
work fine.
now I try to access the two bots from a single frequi session, and it tells me:

 Login failed.
Please verify that the bot is running, the Bot API is enabled and the URL is reachable.
You can verify this by navigating to http://192.168.1.176:8081/api/v1/ping to make sure the bot API is reachable 
 Please also check your bot's CORS configuration: Freqtrade CORS documentation

i have pong
and use correct user and password.

thanks

**Comment by bibinvargheset** [comment]
use cor=["http://192.168.1.2:8080"]

**Comment by xmatthias** [comment]
as mentioned above, the documentation covers this.
