### ISSUE TITLE
Switch candles type (add Heikin Ashi)

### ISSUE THREAD

**Issue by ikonx** [freqtrade/frequi#560]
**Is your feature request related to a problem? Please describe.**
I'm using Heikin Ashi candles and i'd like to change candles type on frequi to check my buy/sell signals and tune my strategy.

**Describe the solution you'd like**
Add a way to change our candle type on our UI, maybe add it in the Plot Configurator pop-up.

**Describe alternatives you've considered**

**Additional context**

Keep up the good work!

**Comment by xmatthias** [comment]
you can't use heikinAshi candles at the moment directly, however nothing prevents you from using lines to represent each of the forms.

It's also something i'd consider quite niche - so i don't think we'll be spending any/much time on this (but obviously, contributions are always welcome).

**Comment by xmatthias** [comment]
Closed by #698
