### ISSUE TITLE
Create more graphs than the "default"

### ISSUE THREAD

**Issue by MichaelMacca96** [freqtrade/frequi#561]
With a Previous version of FreqtradeUI it was possible to create more graphs for a single bot.
Now only the default is available, isn't it?

![image](https://user-images.githubusercontent.com/91595678/139603737-b7c75065-76fb-4b45-ad64-184edaacdb2d.png)

Now I'm working with these versions:
Freqtrade    2021.10
FreqtradeUI 0.2.0

Thanks!

**Comment by xmatthias** [comment]
You can use the plot configuration dialog and save that second configuration with a different name to have multiple configurations available.

**Comment by MichaelMacca96** [comment]
Hi xmatthias,

Thanks for your answer.

I can't reproduce what you suggested to me, can you provide an example?

Is it possible to add the second plot code to the Strategy?
Like this:

#Default
plot_config = {
        'main_plot': {
            'ema4': {'color': 'blue'}
            }
   }

#SECOND ENTRY:
plot_config_2 = {
        'main_plot': {
            'ema4': {'color': 'red'}
            }
   }

Thanks!

**Comment by xmatthias** [comment]
You're right, there's been a bug in it causing the 2nd config to not save.

You can't configure different entries in the strategy - usually you'll only have one config per strategy - but potentially one per strategy (which would work).
