### ISSUE TITLE
MultiBot 

### ISSUE THREAD

**Issue by bibinvargheset** [freqtrade/frequi#562]
Firstly let me tell you you have done a great job and please continue to do in future. Some sugession for you so that the experience be nicer to everyone

1. Either add CORS example for local host CORS =["http://127.0.0.1:8080"] in documentation or since the error message is able to convert ["127.0.0.1:8081"]  to ["http://127.0.0.1:8081"]  add that converstion in the program 
2. The bot name is redundant as config file has already a bot name, if those information is added to will reduce confusion and trouble of adding botname. if the bot name is added intially and and can be edited afterwards it would be helpful
3. Add all multi bots automatically, possibly through wehook to origin or other methods, you can ask for confimation from the user once detected.
4. Most people use same config in api section for all bots so if multiple bots with same config can be added in one go it would be good
5. multibot dashboard the percent values are wrong and needs to be corrected 
6. if summary is added to all fields in the dashboard it would be helpful
7. if closed trades are addded it would be good
8. if filtering of single or multiple by selection in the dashbord it will also we be good
9. if there was a option to define the layout from the main config file or a gui config json file for widgets thier size and selection it would be helpful
10. if there was one dashbord with the stats simillar to backtest report with period selection and bots selection from the sql database it would be great.

**Comment by xmatthias** [comment]
1) you clearly don't understand how CORS works - it must be configured correctly before starting the bot to work - and it's covered by the [cors documentation](https://www.freqtrade.io/en/stable/rest-api/#cors).
2) feel free to create a PR adding this (please ensure to not overwrite eventual values the user inserts).
3) Freqtrade (the backend) will not know if/where you're running your UI - and it also has no access to it in a proper setup as recommended by the documentation (running everything in a secured network).

For the rest - best create seperate, detailed issues for each of these (including screenshots where it makes sense) - as it's unclear what you mean or think is wrong - and it'll be a mess to try and clarify 10 points in one issue.

**Comment by xmatthias** [comment]
I think these issues are now covered in seperate issues.
