### ISSUE TITLE
Cors Url in docs

### ISSUE THREAD

**Issue by bibinvargheset** [freqtrade/frequi#563]
Either add CORS example for local host CORS =["http://127.0.0.1:8080/"] in documentation or since the error message is able to convert ["127.0.0.1:8081"] to ["http://127.0.0.1:8081/"] add that converstion in the program

**Comment by xmatthias** [comment]
we have the [CORS documentation](https://www.freqtrade.io/en/stable/rest-api/#cors), which documents how to set this up.

Auto-conversion is not possible - and messing with settings the user inputs would potentially cause unwanted issues, or even security problems, and will thereore not be implemented.

**Comment by bibinvargheset** [comment]
Please add a line shows   ["http://127.0.0.1:8081/"] to avoid confusionit took two days for me to understand and hippo, i had stopped tring until the message on discord.

**Comment by xmatthias** [comment]
I don't really see how `"http://127.0.0.1:8081/"` would be different to `"https://frequi.freqtrade.io"`.
both work, both include both the protocol and the URL (port can be omitted for default ports (80, 443).
