### ISSUE TITLE
multibot dashboard t

### ISSUE THREAD

**Issue by bibinvargheset** [freqtrade/frequi#565]
multibot dashboard the percent values are wrong and needs to be corrected
if summary is added to all fields in the dashboard it would be helpful
if closed trades are addded it would be good
if filtering of single or multiple by selection in the dashbord it will also we be good

**Comment by xmatthias** [comment]
with the information provided, i'll have to tread this as "not enough information" issue - so i'll label it "question" for now (might change in the future, if more information is provided).

If you think something is wrong, please provide a screenshot highlighting the issue / values you think are wrong - as well as what you think would be correct and based on what assumption.

If you desire additional fields / additional summaries - best also use screenshots to show where these should be added.

**Comment by bibinvargheset** [comment]
in this image you the closed profit is 17.66% (41.506)   the percent should be 4.1506 (41/1000) simllarly in the case of open profit.
If the cumamulative profit and daily profit  can be filtered by selecting bots it would be good
if the closed trades list on trade page can added to this page also it might be easier

![image](https://user-images.githubusercontent.com/51453234/140025675-63e009a8-72d4-4237-91e9-1d1801db9526.png)
