### ISSUE TITLE
Layout

### ISSUE THREAD

**Issue by bibinvargheset** [freqtrade/frequi#566]
if there was a option to define the layout from the main config file or a gui config json file for widgets thier size and selection it would be helpful

**Comment by xmatthias** [comment]
The layout is something that's custom to freqUI - and can change at any point in time independent from freqtrade itself.
It's also possible to run freqUI independent from freqtrade (via https://frequi.netlify.app/ for example) - where you'll have no backend that defines this.

It would also only create confusion if you have multiple bots with conflicting layouts - therefore this is not something we'll be looking to support.
