### ISSUE TITLE
Login Username field always marked as invalid

### ISSUE THREAD

**Issue by kevinehosford** [freqtrade/frequi#575]
**Describe the bug**
I installed using docker-compose and the quickstart documentation. I can see the login screen however the "Username" field is marked as invalid when I "Submit".

**To Reproduce**
1. Install using https://www.freqtrade.io/en/stable/docker_quickstart/ with the freqUI enabled.
2. Open a browser and visit http://localhost:8080
3. Fill out the form fields

**Expected behavior**
Since the input is filled out I don't expect to receive the "Name is required" validation message.

**Screenshots**
<img width="516" alt="invalid" src="https://user-images.githubusercontent.com/18267875/140668955-3f80f0a6-c839-409b-8b50-661ed78ef00e.png">

**Desktop (please complete the following information):**
 - OS: macOS Big Sur
 - Browser Chrome (95.0.4638.69) and Firefox (92.0)

**Comment by kevinehosford** [comment]
It seems like this is because I left password empty.

**Comment by xmatthias** [comment]
yes that's correct. I've updated the wording here sligtly in 2f2edb3, so this should become clearer.
