### ISSUE TITLE
Buy/Sell Signals are not plotted anymore

### ISSUE THREAD

**Issue by maumi** [freqtrade/frequi#582]
**Describe the bug**
Since I updated today Freqtrade the buy and sell signals are gone at the chart.
I know and see there should be signals, it's also written next to the reload button pe "Buysignals: 116
SellSignals: 150".
Also in the "Tooltip" for each candle there are many values written, I gues these are the values from the strategy to buy or sell.
But they are written in one line with a high decimal place.
Maybe you could redesign this a little bit.
**To Reproduce**
Just go into the frequi Graph tab.

**Expected behavior**

**Screenshots**
If needed (because not clear or reproducible, I can add screenshots.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Safari
 - Version 0.20

**Comment by xmatthias** [comment]
If you're using the latest develop version, please make sure to also upgrade freqUI.

I try to keep the 2 aligned - but it's up to the user to also update freqUI (the latest version of freqUI is 0.2.1).

**Comment by maumi** [comment]
Thanks. Because it is the dev branch it is totally understandable that you can't have Them always aligned.
