### ISSUE TITLE
Multibot issue error forcesell and delete trade.

### ISSUE THREAD

**Issue by anakein** [freqtrade/frequi#590]
Hi;  Into dashboard, when you try forcesell or delete trade, dont work if you have selected other bot.

I have 2 bots, Bot1 and Bot2,  i have open trades both bots., if i have selected in upper website  bot1(both checkbox cheked) and i try delete bot2 trade, show me error, or delete bot1 trade id.

**Comment by xmatthias** [comment]
For the moment, i'd recommend to not use the action buttons in the dashboard view. I'll see to hide them from that view, so they're not "tempting" anymore.

**Comment by xmatthias** [comment]
Will be fixed with the next release
