### ISSUE TITLE
page unresponsive

### ISSUE THREAD

**Issue by AmirMassou94** [freqtrade/frequi#599]
**Describe the bug**
on webserver mode (freqUI v:0.2.2) after clicking Back-test / Graph page become unresponsive with using a lot of CPU usage and at the end you have to kill it
it happend in Edge and chrome but running well with mozila with no problem

**Desktop **
 - OS: [Ubuntu]
 - Browser [chrome, edge]

**Comment by xmatthias** [comment]
we'll need a bit more information for this.
How many indicators are specified in the graph
what timeframe was selected
how many trades did backtesting perform

**Comment by AmirMassou94** [comment]
When I start webserver, then clicking the backtest button nothing appears so at this level I didn't select any strategy or not even selected any timeframes and other parameters!

**Comment by xmatthias** [comment]
best post a screenshot from what you are seeing, so we can check it best (and it will avoid missunderstandings).

also, please check the console logs (you can usually get to these by pressing F12 in your browser.

**Comment by xmatthias** [comment]
Closing this as there has been no additional info for several months.
