### ISSUE TITLE
"Login failed" when trying to add an external bot

### ISSUE THREAD

**Issue by pizzidellamaremma** [freqtrade/frequi#606]
I'm in a 2021.11 stable container environment, first trader on port 8001, second trader on port 8002.
Everyone responds correctly by web browsing.
When I try to add a bot inside the other it gaves me "Login failed". The same happens when using IP addresses. Am I missing something?
![issue](https://user-images.githubusercontent.com/39835713/145248803-2c907e42-fb06-4c0c-80d5-310880b55c96.png)

**Comment by xmatthias** [comment]
The error points you to the [CORS documentation](https://www.freqtrade.io/en/stable/rest-api/#cors) - which you should follow for this to work correctly.

**Comment by xmatthias** [comment]
I'll assume this as answered as there has been no further activity for several months.
