### ISSUE TITLE
Settings page renders `\n`

### ISSUE THREAD

**Issue by MNThomson** [freqtrade/frequi#607]
**Describe the bug**
In the `Lock Layout` option on the settings page, a `\n` is shown in text instead of rendering a newline.

**To Reproduce**
1. Open FreqUI
2. Go to the settings page

**Expected behavior**
The `\n` should not be visible to the user. Be it just removed or a proper newline is created.

**Screenshots**
![Screenshot from 2021-12-09 02-15-40](https://user-images.githubusercontent.com/73045936/145378837-968c47b4-ccb9-49e0-888d-60272b495092.png)

**Desktop**
 - OS: Pop!_OS 21.04
 - Browser: Firefox
 - Version: 94.0

**Additional context**
I tried to force a newline to render with `\r\n`, `&#13;&#10;`, `&#10;`, and adding a physical line break in the code. However nothing I tried successfully added a newline, otherwise I would have opened a PR.

**Comment by xmatthias** [comment]
ah, it's a security feature of vue, not allowing you to render html (the correct value for a linebreak would be `<br />`).
It's not necessary however (not sure what my intend was with this), so I've simply removed the newline.
