### ISSUE TITLE
Floating Menu blocking chart.

### ISSUE THREAD

**Issue by betancourtl** [freqtrade/frequi#642]
Hi, I'm trying to use the freqtrade charts but the floating menu takes most of the chart. Is there a way to disable this?
![Screen Shot 2022-01-16 at 8 56 56 PM](https://user-images.githubusercontent.com/7534346/149689199-a91790fb-ab75-488e-b7c5-530eeb627889.png)

**Comment by xmatthias** [comment]
I've moved this issue to the freqUI repository, as that's where it belongs.

the "floating menu" is called a tooltip, and will show you the actual values.

It will only appear when you hover your mouse over the chart, so simply moving the mouse out of the chart area will make it disappear.

I also think that you're using an old version of freqUI ... as it should no longer be this big.

**Comment by edu2004eu** [comment]
Am seeing the same with frequi 0.2.5 which was installed along with freqtrade 2022.01 (using docker).

**Comment by xmatthias** [comment]
works fine for me on 0.2.5 :) 

![image](https://user-images.githubusercontent.com/5024695/152655886-f58850e6-3a4c-4ece-885b-4661769f5d71.png)

**Comment by xmatthias** [comment]
Closing this as i think your question has been answered, and this has been fixed.

Feel free to comment below / reopen if it's still unclear.
