### ISSUE TITLE
save information in json file

### ISSUE THREAD

**Issue by anakein** [freqtrade/frequi#643]
I think that a good option would be that we can save a certain candle with all the indicators that we have active. When making strategies, it would be very interesting to be able to have specific moments of a pair.

for example:
If we click on a candle, and we give the save option, it would save the data of the candle, open, close, RSI, MACD, etc... values, and so on with all the indicators that we have activated.

**Comment by xmatthias** [comment]
To be honest, i don't think freqUI is the right tool for that.

The moment you move the mouse to the "save" button, you'll have a different line highlighted - so from a usability perspective, it'll automatically be very bad.

if you need the data for a specific moment based on your strategy analysis, i'd recommend the [strategy analysis](https://www.freqtrade.io/en/stable/strategy_analysis_example/) notebook.

You'll get the whole dataframe in an interactive environment, which you can then use to explore these further.
