### ISSUE TITLE
Docker compose build fail on raspberry pi

### ISSUE THREAD

**Issue by elestranobaron** [freqtrade/frequi#696]
Hey, I fixed the incompatibility version from docker-compose.yml from 3.8 to 3

Then added --network-timeout 100000 to yarn to fix "network connection error"

then i got this error:

Output:
The Cypress App could not be installed. Your machine does not meet the operating system requirements.

https://on.cypress.io/guides/getting-started/installing-cypress#system-requirements

Thanks

**Comment by xmatthias** [comment]
It's unclear what you're trying to do - but considering that freqUI is now available via freqtrade - i don't think this will be necessary.

We are aware that building the docker-file on arm machines can cause errors (not necessarily with cypress) - but so far, i've encountered no good reason trying to run it this way either.

**Comment by elestranobaron** [comment]
"freqUI is now available via freqtrade"

Didn't know that thanks, How do i access ui ?

**Comment by xmatthias** [comment]
the [documentation](https://www.freqtrade.io/en/stable/rest-api/#frequi) got you covered.
