### ISSUE TITLE
Prefer Typescript to Javascript ?

### ISSUE THREAD

**Issue by gaugau3000** [freqtrade/frequi#7]
Hi,

I don't know the level of logic you would like to put at the end in this project but typescript should be useful to ensure a high quality and reduce bug up front.

It will help developers too with hint and auto completion in there IDE.

**Comment by xmatthias** [comment]
Found a pretty good ressource on this: https://blog.logrocket.com/how-to-write-a-vue-js-app-completely-in-typescript/

**Comment by xmatthias** [comment]
I'll close this as almost the complete code is now in typescript as of 54463d7 .

Future improvements will be made moving along - but i think using typescript does make perfect sense.
