### ISSUE TITLE
Api url should be used on requests for docker deploy

### ISSUE THREAD

**Issue by betogontijo** [freqtrade/frequi#71]
**Describe the bug**
After logging in all request are made to the same port as frequi is running resulting on http 404.

**To Reproduce**
Just build with docker and deploy

**Expected behavior**
All request be made to the configured url on login

**Screenshots**
This was a simple change I've made to solve the problem
![image](https://user-images.githubusercontent.com/7017742/90718786-340ebf00-e289-11ea-9d33-08999c39bb41.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser Chrome
 - Version 2020.7

**Comment by xmatthias** [comment]
Well when you login, you have to provide a URL. If you don't change that url, it'll use "itself" - which obviously will fail.
so you have to provide the url where the bot API is reachable - or the bot needs to run under localhost:8081 (which is proxied by webpack when running in develop mode (using `yarn serve`) - but this won't work in "production" mode).

However, we cannot know where your bot is running (could be local, could be remote, could be on the moon for all we can guess) - so you have to insert the correct address - and not leave the URL as is.

![2020-08-20-071746_520x441_scrot](https://user-images.githubusercontent.com/5024695/90719666-43a3fd00-e2b5-11ea-8ec7-6b61ecdbeeef.png)

**Comment by xmatthias** [comment]
After verifying, you're right - this happens when login is done via the modal. There is another (hidden) login form, which does not suffer from this - as it'll reload the page.

Thanks for reporting and fixing (next time, maybe consider doing it as PR - as my fix is basically a replication of your screenshot ...).
