### ISSUE TITLE
signal condition tag.

### ISSUE THREAD

**Issue by anakein** [freqtrade/frequi#738]
could I signal condition tag?, i see trade tag into trade infomation ( this is perfect), but into chart to show signal condition is good for to know signal without trades.

thanks

**Comment by xmatthias** [comment]
that's probably not possible in the short term.
the tooltip (where this would belong) is auto-generated, and we currently have no plans on generating that manually - as that would be quite complex to get right with all the dynamic indicators that are possible.

**Comment by anakein** [comment]
ok. thanks but...
Is there a way to know the reason why we have buy signals but the not trade?.

**Comment by xmatthias** [comment]
this can have many reasons - either you don't have enough money, a trade for this pair is already in progress, no more trade slots available, signals are colliding, ...

**Comment by xmatthias** [comment]
The trade tags are now available (since 0.4.0) in the tooltip of the chart.


![image](https://user-images.githubusercontent.com/5024695/175105121-cdc4f4fe-df72-478c-b478-7ba456f2aba5.png)
