### ISSUE TITLE
ability to specify the columns and candle limit to fetch for the chart manually

### ISSUE THREAD

**Issue by shayan775** [freqtrade/frequi#798]
i was working with ```ferqai``` branch. as you may know in AI strategies you'v got to work with so many columns, the API that fetches the candle rows, fetches all the columns too, and with the limit of 500 rows by default, in many cases the ```pair_candles``` API time's out because of the large number of rows and columns.

if there was a way to specify the columns you want and/or set the limit parameter manually, it would be so helpful in many cases to reduce the volume of the data transferred and prevent timeout. 

increasing the timeout also  works if its possible of course.

thnks.

**Comment by xmatthias** [comment]
Please make sure to use the latest version of freqUI (simply run `freqtrade install-ui` to get the latest version).

We're no longer passing the "limit" parameter when fetching candles - so you'll get all the candles freqtrade (as backend) has to offer.

I'm not sure how you'd imagine a "reduced column-set" to work. 
FreqUI still needs to know about all columns (so you can select them) - but the UX aspect of selecting this (and then getting the correct data back) is not a hastle i'll get into anytime soon.

If you think there is a problem with the timeout, please provide full information (used freqUI version, screenshots / logs from the browser showing which request in particular did time out).

**Comment by xmatthias** [comment]
Adding to this for freqAI in particular: 
maybe consider not keeping the whole model data in memory - but only the "relevant" columns (basically the dataframe `populate_indicators()` returns only contains some key columns (the ones you want to visualize / use for the prediction) - as well as the prediction column?

looping in @robcaulk - as i'm sure he has an opinion (or at least thought) about this, too.

**Comment by robcaulk** [comment]
@shayan775 has a good point. The current interface freqai lets the user create features in the strategy. If the user wants 1k features, this is 1k columns and 1k columns for frequi to load (I think, I am not deep into how frequi is operating, but I know we can select any indicator we want to plot). 

So one really easy solution here is to simply filter out any indicator starting with % from the dataframe before sending it to frequi to process. This would remove all the useless freqai features. It would not remove the important information that freqai returns, namely `prediction`, `target_mean`, `target_roi`, and `do_predict`. Those are the quantities that we need to plot in frequi.

**Comment by robcaulk** [comment]
Actually, we could filter all the prepended `%` indicators out automatically in freqai before even returning the dataframe back to the strategy. In other words, the strategy would send a dataframe out to freqai with all the  thousands of `%` feature columns but it would get back a dataframe without any of that included. Would this help frequi? Does it fit into how frequi interacts with the strategy dataframe?

**Comment by xmatthias** [comment]
honestly, it's not just a freqUI problem - freqUI (or rather the API) is just accessing the (cached) dataframe as is (with some slight alterations to allow for easy datetime parsing).

if you keep 1k columns in the dataframe (basically what is returned after all `populate_*()` methods have been executed) - then this dataframe with 1k columns will be kept in memory until the next candle (assuming you have `process_only_new_candles=True`).

if there's columns (features?) which are not needed past freqAI processing - then i'd assume these can/should be filtered out beforehand anyway.

Now the dangerous part is: 
even if RSI (or any other regular indicator) is a feature freqAI used - i may want to still keep that to display it - simply because it's my indicator of choice.
so simply removing "everything" MAY be a dangerous premisse, too.

**Comment by xmatthias** [comment]
specifically for freqAI, you can use the following snippet as part of your `populate_indicators()` method (deposit it right before the `return dataframe`.


``` python
        # ...
        to_keep = [col for col in dataframe.columns if not col.startswith('%') or col.startswith('%%')]
        dataframe = dataframe[to_keep]
        return dataframe

```

This will reduce the amount of columns from the few 1000 features used to only the ones that start with %% - and the ones not included in the model.

**Comment by robcaulk** [comment]
> 

This is no superceded by automatic handling in the backend. User no longer needs to add this to strategy.
