### ISSUE TITLE
Bootstrap Vue or Vuetify ?

### ISSUE THREAD

**Issue by gaugau3000** [freqtrade/frequi#8]
Hi,

From what i have seen is the code use BootstrapVue :-).
Just would like to mention Vuetify because it is the early stage of the project.

Because they have a LTS support, the doc is very readable, custom components css is easy with sass variables.

But you have to like material design. Has has see freqtrade ui like dashboard material design is a not so bad.

Have a nice day.

**Comment by xmatthias** [comment]
well the main point for bootstrap for me was that it's based on bootstrap - which means more people are likely to be familiar with.

Initially, i didn't want to go to bootstrapVue - but to plain bootstrap, until i read that it'll be problematic if both jquery and vue manage DOM ...


---

Vuetify seems to be very much limited to Material themes (at least i couldn't find non-material ones readily (and freely) available) ... which to be honest, i used to like but find kinda boring now (just look at the Sketchy theme we got in the UI right now ...) :laughing:

**Comment by gaugau3000** [comment]
> well the main point for bootstrap for me was that it's based on bootstrap - which means more people are likely to be familiar with.

I agree.

> Initially, i didn't want to go to bootstrapVue - but to plain bootstrap, until i read that it'll be problematic if both jquery and vue manage DOM ...

Honestly have vue components that manage the javascript witch is what provide bootstrapVue , vuetify, bulma... is really helpful. With JQuery unified javascript browser but hard too test, no scoped...

> Vuetify seems to be very much limited to Material themes (at least i couldn't find non-material ones readily (and freely) available) ... which to be honest, i used to like but find kinda boring now (just look at the Sketchy theme we got in the UI right now ...) 😆

Sketchy theme is very funny :-) (remind me when i use balsamiq mockup at the beginning of projects).
My concerns are more about the maintenance than design (because sure freqtrade should not reinvent UI and UX :-) ).

**Comment by gaugau3000** [comment]
You can see top css framework stats that work with vue [here](https://www.youtube.com/watch?v=jzYsq6OafVk) vuetify and bootstrap vue are clothed.

**Comment by xmatthias** [comment]
> My concerns are more about the maintenance than design (because sure freqtrade should not reinvent UI and UX :-) ).

why / what makes vuetify easier to maintain than bootstrap-vue?

**Comment by gaugau3000** [comment]
Because he have a long term support and he implement material design specifications that ensure constraints and best practices during ui development so limit bad ux design choices and so custom code with and maintenance related.

**Comment by xmatthias** [comment]
Well, I've looked at popularity (difficult to measure i guess) - [npm downloads](https://www.npmtrends.com/bootstrap-vue-vs-vue-material-vs-vuetify) seem to suggest they both are similarily popular.

well that's the problem - vuetify will only ensure that single components adhere to material constraints - but it can't enforce the overall design adheres to this.
example: it can enforce that a button will look like a material button - but not how i place this button (partially hidden below another button) ... so it might give a false sense of security.


---

while LTS seems to be a point for business adoption, but i've never seen a point in that - and try to stay away from LTS stuff as far as possible. 

If you think about how a project maintains LTS Releases (no matter which project): 
* develop using the latest version
* decide "this we need in LTS" - and then try to backport it without breaking LTS

I'd rather use the latest version - which is where this feature/bug/whatever was developed for.

Also, it'll only really have an impact if there is a big breaking change - but it won't prevent upgrading - just delay it until LTS runs out eventually (windows7, i'm looking at you).

--- 

in the end, the main selling point would have been "vuetify is used by 90% of vue projects, bootstrap-vue by 10%` ... but that doesn't seem to be the case if we look at the numbers.

**Comment by gaugau3000** [comment]
You are right about LTS.

> well that's the problem - vuetify will only ensure that single components adhere to material constraints - but it can't enforce the overall design adheres to this.

yes that is true it is sad but we have to think the design :-) 

> example: it can enforce that a button will look like a material button - but not how i place this button (partially hidden below another button) ... so it might give a false sense of security.

what i try to explain that UX designers have think about design when producing material design and so there are props in vuetify that permit to apply this rules easily. Of course you can do anything with UX and produce bad things.

Stay on bootstrap is fine, this was an interesting conversation

I keep it open 1 month if some people have a strong opinion about it and then i close it.

**Comment by xmatthias** [comment]
Just to throw in 2 additional UI frameworks that were suggested on slack:

* [semantic-ui](https://semantic-ui-vue.github.io/)
* [antd](https://antdv.com/docs/vue/introduce/)

**Comment by xmatthias** [comment]
will close this as i think we'll not switch framework at the moment ... however, the discussion and links will remain available anyway.
