### ISSUE TITLE
No shorts label displayed if strategy has no exit_short == 1 in dataframe returned

### ISSUE THREAD

**Issue by farmage** [freqtrade/frequi#839]
**Describe the bug**
Spent few hours trying to figure out why Shorts labels are not displayed
I'm using custom_exit in my strategy, so exit signals are not essential for me.
So, if the populate_exit_trend returns dataframe without changes or it has no any exit_short == 1 , the chart will not display any Short labels. Meanwhile, Long labels will be displayed without any problem

**To Reproduce**
1. Create a simple strategy
2. Use such code dumb
```
    def populate_exit_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
       # just return dataframe without changes
       # return dataframe

        # LONG exit checks
        dataframe.loc[
        (
            (dataframe['volume'] > 0)
        ),
        'exit_long'] = 0


        # SHORT exit checks
        dataframe.loc[
        (
            (dataframe['volume'] > 0)
        ),
        'exit_short'] = 0

        return dataframe
```
3. You will no see any Short labels anymore

**Comment by xmatthias** [comment]
Its unclear what you mean with "short labels".
Maybe provide a screenshot showing the piece you found missing when exit signals are absent, or try to explain better what exactly you are missing.

**Comment by farmage** [comment]
As you can see on this picture, the green "Short" arrows displayed
![Screenshot from 2022-07-02 16-02-54](https://user-images.githubusercontent.com/82975149/177002009-2c3bbaf1-8290-4df8-8fd5-62f9d864c338.png)

The same chart, but there is no "Short" arrows
The only difference in strategy code, there is no exit_short==1 signals in the dataframe
In this strategy I use custom_exit and close orders real-time on condition
![Screenshot from 2022-07-02 16-01-55](https://user-images.githubusercontent.com/82975149/177002013-ef5d3c7f-b4ff-4d8d-b5e8-0650d239b698.png)

**Comment by xmatthias** [comment]
Will be fixed in the next release.
