### ISSUE TITLE
FreqUI does not load

### ISSUE THREAD

**Issue by marcelo-o** [freqtrade/frequi#878]
As of version >= 0.2.7 the following error occurs and the page does not load and just displays a black background.

`Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec.
`

I'm running FreqUI installed through freqtrade windows installation.

Would I have to apply some extra configuration?

<img width="960" alt="image" src="https://user-images.githubusercontent.com/32903573/181519208-37526fc6-d157-4305-8066-f4c69e73f478.png">

OS: Windows 10
Browsers: Chrome, Brave, Firefox

**Comment by xmatthias** [comment]
what's your freqtrade version?

Best use CTRL+R to reload the site (with freqUI open). That'll show you the request in the network tab.
Using a (mostly) recent version of freqtrade - i do get the proper content type - so the most likely reason is that either freqtrade, or dependencies for it are outdated.

![image](https://user-images.githubusercontent.com/5024695/181602832-1f73db01-7a41-413f-889f-dc34f1f9326d.png)

**Comment by marcelo-o** [comment]
Ok, I made sure I have a fresh browser and no cache.
Installation is clean and version is `freqtrade 2022.6`

But I get text/plain as content type.

<img  alt="image" src="https://user-images.githubusercontent.com/32903573/181613740-2c500239-6b66-41c1-a935-601080366b67.png">

The version that is working for me is 0.2.6 installed through `freqtrade install-ui --ui-version 0.2.6`.

Thanks!

**Comment by xmatthias** [comment]
I can't really recreate this on an uptodate freqtrade installation - it works just fine for me with the very latest version (0.4.2).

Please ensure that not just freqtrade is on 2022.6 - but that it's been updated correctly (including all dependencies).
you may want to run `pip install -r requirements.txt` for this again (and then restart the bot, obviously) to ensure dependencies are uptodate.

**Comment by marcelo-o** [comment]
I will investigate this further and any news I bring here.

**Comment by ziiiliu** [comment]
@marcelo-o I ran into the same issue - have u managed to solve it?

**Comment by xmatthias** [comment]
Please look at https://github.com/freqtrade/freqtrade/issues/7147#issuecomment-1200424047 for more details on a fix.
You can also use https://github.com/freqtrade/freqtrade/issues/7147#issuecomment-1200412553 to test what the outcome on your system is.

It's a system configuration issue - which will affect all applications on your system.
for freqtrade, the latest develop version will enforce this type - but i think having this misconfigured, you can expect further problems in other applications if this is not corrected.
