### ISSUE TITLE
Actions popup doesn't work on Safari

### ISSUE THREAD

**Issue by sfDuhNinja** [freqtrade/frequi#899]
**Describe the bug**
On latest version of Safari and macOS the Actions menu does not show up. On Brave I can see the Forceexit/Delete trade options, but on Safari it does not work as intended. On Safari I have disabled the adblocker, but the behaviour is the same.

**To Reproduce**
1. Go to Trades > Open Trades
2. Click on Actions button

**Expected behavior**
The menu for manual closing the trade should pop up

**Screenshots**
![Captură de ecran din 2022-08-19 la 12 29 01](https://user-images.githubusercontent.com/27433856/185589653-8d67f436-2176-4ddb-a077-a534f320e53b.png)
![Captură de ecran din 2022-08-19 la 12 29 18](https://user-images.githubusercontent.com/27433856/185589658-0583e3db-18f6-41db-8c9f-975f4ff3bbf7.png)

The first screenshot is from Safari and the second one is from Brave

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Safari
 - Version 15.6

**Comment by xmatthias** [comment]
best check the developer console log (assuming safari has such a thing) and hope it contains something useful.

I'm unable to test on safari - so unless you are able to identify WHAT is causing this, the recommandation will be to use a proper browser.
