### ISSUE TITLE
Chart scaling issue when overlapping multiple indicator

### ISSUE THREAD

**Issue by xarthurx** [freqtrade/frequi#922]
**Describe the bug**
When adding more indicators to the chart in webUI, many indicators are overlapped into one chart.
Due to the unit difference on the Y-Axis, this will cause the chart scaled improperly.

**To Reproduce**
1. Go to webUI 
2. Click on "Settings" (top right corner)
3. Add an indicator with different unit (e.g. rsi)
4. See how the chart is scaled.

**Expected behavior**
We should separate the addtional chart. For indicators that not associated to the candle, we can separate them out to an independent chart.

**Screenshots**
![image](https://user-images.githubusercontent.com/1921878/188570108-dd3dc252-cf73-42e7-ab7a-30b9d8c67d10.png)

![image](https://user-images.githubusercontent.com/1921878/188570223-61a081a1-c178-40fe-9570-5e3a48db67c9.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 22

**Comment by xmatthias** [comment]
You can use the chart-editor (wheel at the top right) to add sub plots - and then add indicators to these subplots (select them in the chart editor).

one thing that can and should be improved is the chart-editor itself  as it can be sometimes confusing - but the possibility is clearly there.
If your plot configuration comes from the strategy - you can configure this by using the "subplots" feature - as described in [this page](https://www.freqtrade.io/en/stable/plotting/#advanced-plot-configuration).

The plot configurator has the same possibilities - and will generate a configuration compatible with the plot-configuration shown in the documentation.

**Comment by xarthurx** [comment]
Thanks.

From several questions, I asked from yesterday and your responsive answer, I can see the documentation is really well made. I appreciate it a lot!
