### ISSUE TITLE
Dark Mode set with checkbox on settings page

### ISSUE THREAD

**Issue by klara31** [freqtrade/frequi#931]
**Is your feature request related to a problem? Please describe.**
FreqUI always starts in dark mode, even if I switched it off.

**Describe the solution you'd like**
Make dark mode a setting on the FreqUI settings page with a checkbox

**Comment by xmatthias** [comment]
This was actually already implemented - but it appears like it didn't "survive" some changes to how settings are stored.

Will be functional again with the next release.
