### ISSUE TITLE
change Y axis value to porcentual

### ISSUE THREAD

**Issue by anakein** [freqtrade/frequi#947]
exactly it.
change y-axis from value to percentage for to see percentages and not crypto value.

thanks

**Comment by xmatthias** [comment]
This is currently not possible - and will also not be something we'll look into incorporating into freqUI.

The purpose of the chart is to show you the indicators the way freqtrade sees them. 
if the UI now changes the values to % values, then all indicators would have to be recalculated - which would most likely result in different results - as we'll not know your parameters to calculate whatever value.
