### ISSUE TITLE
Mark rejected signals on chart

### ISSUE THREAD

**Issue by fillobotto** [freqtrade/frequi#975]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I'm working on a strategy that generates lots of signals from technical indicators but then they are mostly rejected inside `confirm_trade_entry` method where I also look at ticker / order book data.

It would be a nice thing if rejected signals were shown slightly different on freqUI charts.
(Maybe in the future we will be able to reject signals with a `reject_reason` and freqUI could display it)

**Comment by xmatthias** [comment]
i'm afraid that's not going to work - and you shouldn't use confirm_trade_entry as a main source of valid signals.
you'll see that this will become very verbose in live - and performance will suffer from this as well - as a valid entry-signal is checked once per iteration (by default roughly every 5s) for the duration of the signal being there, so depending on the work you do in there, you might encounter performance problems, too.


In general - freqUI will only be able to visualize information that is generated by populate_* methods.

Running callbacks and is not in scope for the chart (this would kill performance of a "get candles" request) - and will therefore not be implemented.
