### ISSUE TITLE
bars accumulated to the right of the screen when switching between bots

### ISSUE THREAD

**Issue by xarthurx** [freqtrade/frequi#991]
**Describe the bug**
When using a freqUI connecting to multiple bots, and switching between the bots, after several switches, the bars drawn will be accumulated to the left of the screen.

A refresh of the webpage will fix the issue.

**To Reproduce**
1. Set up connection of multiple bots
2. Switch to bot A,
3. Switch to bot B,
4. Switch to bot A, ( repeat 1-2 times about the above process)
5. See error

**Expected behavior**
bar graph is drawn correctly.

**Screenshots**
![image](https://user-images.githubusercontent.com/1921878/198987892-4b8e24d6-63b4-4fb8-be0a-644b0dbda755.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: newest

**Comment by xmatthias** [comment]
It's not immediately clear what's happening - and i can't seem to reproduce this particular issue for now.

once this happens - could you check if there's something "on the left" of the chart?
Also, if you open devtools (f12) - and open the console is there anything that's in the logs during the time you're running this?

**Comment by xarthurx** [comment]
I don't see anything abnormal.
There is nothing "on the left".

I switched a SQL database and it seems I cannot reproduce this issue. -- it's been there for weeks.

I'll update with this issue if it appears again.

(I'm using the UI with 2022.09 version. And I updated to 2022.10 yesterday, perhaps that might be also another reason?)

**Comment by xmatthias** [comment]
i doubt that there'll have been a "magic" fix - not with the released versions anyway.

i MAY have fixed it over the weekend (while i was playing with something else) - but i've never been able to recreate what you've seen above - so i can't be sure.

**Comment by xmatthias** [comment]
As we've seen no further comment here i'll assume this as fixed (i also can't reproduce it any longer, even though there was no explicit action taken for this problem)
